### ISSUE TITLE
Cannot mine blocks with the wrong tool

### ISSUE THREAD

**Issue by Neko2n** [Insane-96/IguanaTweaksReborn#145]
If a block is too hard for a tool to mine, it will take an infinite amount of time to mine similar to how obsidian works when mined with anything below a diamond pickaxe. For instance, if you try mining diamond ore with a stone pickaxe you will not be able to break it.

If possible, it would also be cool to get a config to change the tool requirement for certain blocks to allow modpack authors to restrict the breaking of certain blocks behind other pickaxes at will.

**Comment by Insane96** [comment]
Actually you can break obsidian with any pickaxe

**Comment by Neko2n** [comment]
Ngl in the roughly 7-8 years I've been playing Minecraft, I never knew that. Guess I just never bothered to try and wait for it to break.

**Comment by Insane96** [comment]
There are actually a few cases:
* A block cannot be harvested at all (e.g. bedrock)
* A block can be harvested by hand and has no efficient tool to be mined (e.g. torches, tall grass, glass)
* A block can be harvested by hand and has an efficient tool to be mined (e.g. wood)
* A block can only be harvested with an effective tool (e.g. stone)

In which cases this feature should apply? (Obviously not the first one)
