### ISSUE TITLE
Use ToolType to check if an item is a Hoe, rather than checking if it extends HoeItem

### ISSUE THREAD

**Issue by Mike-U5** [Insane-96/IguanaTweaksReborn#153]
Not every mod makes their Hoes extend HoeItem. Notably, mods that add multitools and Tinker's Construct.

It might be a good idea to replace **instanceof HoeItem** check with ToolType checks for better compatibility.

**Comment by Insane96** [comment]
Reminder for me

Only present here: https://github.com/Insane96/IguanaTweaksReborn/blob/076d96990309c07d7d8577f1b698274d1d9b7fdb/src/main/java/insane96mcp/iguanatweaksreborn/modules/farming/feature/HoesNerfsFeature.java
