### ISSUE TITLE
Kelp generating bedrock

### ISSUE THREAD

**Issue by MrEcko19** [Insane-96/IguanaTweaksReborn#155]
I guess when kelp is recieving a tick for growing above water level is genereting a bedrock block above them.

![image](https://user-images.githubusercontent.com/84233473/119044819-93cdfe00-b9b2-11eb-8145-93d7e3b9fa25.png)

**Comment by Insane96** [comment]
AHHAHAHAHAHAHHAHAHAHAHAHAHAHAH. Removed 2.5.8 from curseforge.

**Comment by MrEcko19** [comment]
Nice! I'll wait for the update for 1.16.5 then :D
