### ISSUE TITLE
Enchantment for Armor Weight Feature don't apply to non-specific armors

### ISSUE THREAD

**Issue by Xablauzero** [Insane-96/IguanaTweaksReborn#161]
**Versions**: 2.5.9
* Minecraft: 1.16.5 
* Forge: 36.1.23
* IguanaTweaks Reborn: 2.5.9
* InsaneLib: 1.1.0

**What Happens**:  
So, when changing the config file in the [Movement] topic, there is a bug about weighted armor reduction with enchantments not working on mods armors, and i can't find an option to make it work like 'disable mods armor:' or something like that. The vanilla armors are working fine, while all the modded ones don't, making it not viable to use at endgame even if it's better.

**Logs / Crash reports**: https://ghostbin.com/paste/B7A5O

**Config**:  https://ghostbin.com/paste/ymeRQ

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**: I'm not sure.

**Comment by Insane96** [comment]
Please, test out with only IguanaTweaks and the mod with the armor not working.

"I'm not sure" is not an answer.

**Comment by Insane96** [comment]
Managed to find out what's the problem, fixing.
