### ISSUE TITLE
All armors make it impossible to move

### ISSUE THREAD

**Issue by imperialR3D** [Insane-96/IguanaTweaksReborn#163]
**Versions**:
* Minecraft:  1.16.5
* Forge: 36.1.32
* IguanaTweaks Reborn: 2.5.11
* InsaneLib: 1.1.0

**What Happens**:  
Whenever I wear any armor it renders me unable to move. All helmets slow down about 15%, all chestplates slow down about 40%, all leggings slow down about 30%, and all boots slow down about 15%. All of this started happening after I got the new update.

Here is the latest.log folder:
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/6729408/latest.log)

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
yes

**Comment by Insane96** [comment]
You need to regenerate your config if you're using the default one or change all the armor values, as percentages are now set between 0 and 1 in the config instead of 1~100

**Comment by VampireSpaceCat** [comment]
I've regenerated my config, and that's solved vanilla armor and modded armor that uses vanilla materials. But my modded items are still weighing in at 300%s each! What do I do to fix that?

**Comment by Insane96** [comment]
Please open a new issue with the new infos.
