### ISSUE TITLE
[Suggestion] Plants should only grow during daytime

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Insane-96/IguanaTweaksReborn#164]
// Here your suggestion
    As plants undergo respiration during nighttime and require sunlight to be able to grow, the suggestion will add a new difficulty, which I think would fit this mod pretty well. The implementation would furthermore be very similar to the hunger overhaul mod as that mod also has that feature, and would preferably work with modded plants (e.g Farmers Delight, Simple Farming etc).

**Comment by Insane96** [comment]
I'll be adding a growth multiplier when it's night time.
Also should this apply to other plants as well, or crops only?

**Comment by GeorgeOrwell1** [comment]
If you want realism and consistency I would implement it on all _(growable)_ plants, however I personally would think that it could be disabled for certain plants by a blacklisted list in the config file which the player could fine-tune to their own liking (I have no idea how hard or easy that would be to implement, but it'd be appreciated).

**Comment by Insane96** [comment]
Done for 2.6.0
