### ISSUE TITLE
Better Explosions Overhaul Doesn't Respect FTB Chunk's Claims.

### ISSUE THREAD

**Issue by Rensik** [Insane-96/IguanaTweaksReborn#166]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.16.5
* Forge: 36.1.32
* IguanaTweaks Reborn: 2.6.0
* InsaneLib: 1.1.0

**What Happens**:  
Better Explosions seem to ignore whether or not they should happen in an FTB Chunk claim when explosions are disabled in claims.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  

//If different from default
**Config**:  

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
No, need FTB Chunks as well.

**Comment by Rensik** [comment]
... it might be Flying Blocks more so than just Explosions in general as I do have those enabled.

**Comment by Insane96** [comment]
Test if it's flying blocks the problem.

Il Mar 13 Lug 2021, 16:19 Rensik ***@***.***> ha scritto:

**Comment by Insane96** [comment]
No response in > 2 weeks. Closing

**Comment by Proxwian** [comment]
Same problem here. Forge 40.2.2. Minecraft 1.18.2. IguanaTweaksReborn-2.12.11-mc1.18.2.jar

**Comment by Insane96** [comment]
Got no response from the older issue so I can't do much

**Comment by Proxwian** [comment]
I can help you. What I need to do?

**Comment by Proxwian** [comment]
My modpack contains over 280 mods and also SurvivalReimagined plus FTB mods, also on server

**Comment by Proxwian** [comment]
For now setting "Enable Explosion Overhaul" to false fix explosion protection in FTBChunks

**Comment by Proxwian** [comment]
Can reproduce with these mods installed

![image](https://github.com/Insane96/IguanaTweaksReborn/assets/31781674/d929235d-2857-4460-8831-48c9e333d92b)

**Comment by Proxwian** [comment]
Disabling

Disable Explosion Randomness
Knockback Scales With Size
Explosions at Half Entity

Did not help at all. Only "Enable Explosion Overhaul" to false working
