### ISSUE TITLE
Addition to "Punish Wrong Tool".

### ISSUE THREAD

**Issue by Asvort** [Insane-96/IguanaTweaksReborn#170]
"Punish Wrong Tool" there is not enough add-on in the config. 
I need to disable foliage from the list of prohibited blocks.
The problem is that I want the player to be able to break the leaves of the tree with his hand. And I also don't like that the scissors break when the player tries to cut the leaves.

**Comment by Insane96** [comment]
So basically a blacklist.

**Comment by Asvort** [comment]
I meant that the foliage of the tree will be blacklisted if you enable the above setting. Thus, an axe is needed to extract the block, but this is not convenient, and I would like to be able to regain the ability to break foliage with my hand.

**Comment by Insane96** [comment]
No, I'm not gonna add an option just for leaves. I'll add a blacklist where you can put leaves in and will not be affected by "Wrong Tool".

EDIT: Which version are you talking about?

**Comment by Asvort** [comment]
Minecraft 1.12.2.
OK, thanks.

**Comment by Insane96** [comment]
1.12 is no longer supported.
