### ISSUE TITLE
[Combat] Enable Stats = false does not disable changes

### ISSUE THREAD

**Issue by ChiefLogan3010** [Insane-96/IguanaTweaksReborn#172]
**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.0
* IguanaTweaks Reborn: IguanaTweaksReborn-2.6.0-mc1.16.5
* InsaneLib: InsaneLib-1.1.1-mc1.16.5

**What Happens**:  
Setting the [Combat] "Enable Stats" config to false does not disable the changes made to swords and diamond/netherite armor. While it's a minor issue as these can be disabled separately I thought it'd be worth letting you know anyway.

//Please send logs even if you don't have any crash  
Really don't see it helping but if necessary I can add it in a comment

//If different from default
**Config**:  
https://gist.github.com/ChiefLogan3010/a73ff46d0dc239319e9fb3d71b141a5c

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
Yes

**Comment by Insane96** [comment]
Thanks for the detailed report. Will check it in a few days
