### ISSUE TITLE
Modded armor not affected by config reset post update

### ISSUE THREAD

**Issue by VampireSpaceCat** [Insane-96/IguanaTweaksReborn#174]
* Minecraft:  1.16.5
* Forge: 1.16.5-36.2.2
* IguanaTweaks Reborn: 2.5.10+
* InsaneLib: 1.1.1

**What Happens**:  
Modded armor has slowdowns ranging anywhere from 200% to 1100%, depending on how good they are. It seems that however IguanaTweaks decided to calculate modded armor has changed, but their assigned values have not. There are no assigned values anywhere to be found. I do not know how it has decided that Yak Pants have a slowdown of 300%, but I know that it wasn't like that before 2.5.10.

I reset my config after the update that edited the vanilla armor weight values, however my modded armor remains too heavy to use whatsoever. As of right now my config is default.

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
No

**Comment by Insane96** [comment]
An example armor giving the problem? (If can send screenshots even better)

**Comment by VampireSpaceCat** [comment]
These are all screenshots from the latest alpha built. The problem is persistent in all version above 2.5.9
![igtr_normal](https://user-images.githubusercontent.com/88170462/128080981-0f06895b-2d23-4552-aeb5-347c56e6137f.png)
![igtr_glitch1](https://user-images.githubusercontent.com/88170462/128080987-e1fbd35f-8e78-44ed-bc8a-89cad2c9f301.png)
![igtr_glitch2](https://user-images.githubusercontent.com/88170462/128080989-2503e19b-e163-4267-9c0b-9627a4a2ffc9.png)
![igtr_glitch3](https://user-images.githubusercontent.com/88170462/128080993-8a21cf74-83df-4bb7-ac9f-19594fd941e4.png)

Now, here are these same pieces of modded armor using pre 2.5.10 (2.5.9)
![igtr_2 5 9 one](https://user-images.githubusercontent.com/88170462/128081998-50a08c76-bf92-4d8c-a09e-e9cff81fe54a.png)
![igtr_2 5 9 three](https://user-images.githubusercontent.com/88170462/128082002-56db3950-81f2-4f68-9241-4f25784df039.png)
![igtr_2 5 9 two](https://user-images.githubusercontent.com/88170462/128082010-9f15276d-9357-4822-a027-02bc9f28a9d2.png)

One more thing I'd like to note, is that armor that was simply a Piglin friendly rework of Netherite (Gilded Netherite) seemed to mirror Netherite itself, and was not broken.

**Comment by Insane96** [comment]
Could you update to the latest alpha, regen the config and send it?

**Comment by VampireSpaceCat** [comment]
https://pastebin.com/KPqZ2RRT
Armor is still the same. I've noticed that no config options I put in are responding, it's stuck using the default configuration no matter how I set it up. This is true with every version I've tested, even the 2.5.9

**Comment by Insane96** [comment]
I can't reproduce this. Created a new profile and added IT 2.6.0 + Ice and Fire and everything works properly, Modded armors have correct slowdown (like in your screenshots from 2.5.9).

**Comment by VampireSpaceCat** [comment]
Hey, just wanted to give an update. I think it has something to do with the custom server .jar I am using, that allows me to use bukkit and forge together. It's called Mohist! I know it's asking a lot, but please look into it when you've got the time.
It installs a custom version of java for the server to run off of, if that helps! 

To clarify, I was able to boot a world up in single player and the mod was working as intended, using the latest forge 1.16.5 version. Config was responsive and everything. 

When I started a Mohist server using only Insanelib and IguanaTweaks Reborn, the config was still unresponsive.

**Comment by Insane96** [comment]
Did you regen the config in both server and client?
Also make sure to be using the same version on both server and client.

**Comment by VampireSpaceCat** [comment]
Yes, config was regenned for each try, and then edited in several ways. Disabling stack size booleans in both locations, (first on the module part of the config, then within the specific category itself, then both) still resulted in consistent block stacks across all versions tested, (2.2.0 to 2.7.3 alpha.)

**Comment by Insane96** [comment]
EDIT: Just to be clear, Client and Server configs MUST match. Client doesn't get server's config.

I'm so confused right now.
You changed the config then, you didn't try the default config.

Also try creating a new Moisth server with just IT and InsaneLib, and see if it works.

**Comment by VampireSpaceCat** [comment]
Wow! I can't believe I let that simple mistake take us for this whole loop. I'm sorry! The mod is now working as intended on the latest version, specifically after I made sure the client and the server configs were the same. Thanks!!!
