### ISSUE TITLE
Crash with Survive 1.16.5

### ISSUE THREAD

**Issue by The-Brandolorian** [Insane-96/IguanaTweaksReborn#175]
Both Iguanatweaks and Survive are trying to hook into the food mixin and are causing a crash.
[crash-2021-08-09_15.58.08-fml.txt](https://github.com/Insane96/IguanaTweaksReborn/files/6952477/crash-2021-08-09_15.58.08-fml.txt)

**Comment by Insane96** [comment]
Reopen the issue by following the bug report template.
