### ISSUE TITLE
Each Items Stacking Differently

### ISSUE THREAD

**Issue by Niconoko** [Insane-96/IguanaTweaksReborn#18]
It would be nice if there's a white-list to set some specific items to be able to stack differently from the default one, Ex. Set items default stack amount is 4, and want glowstone dust(example) to be stacked up to 16 by put into the white-list and set the amount of it.

**Comment by Insane-96** [comment]
Would you prefer a divider for the stacks, like
`minecraft:glowstone_dust,4`
will make glowstone dust stack maximum at `64 / 4`

Or a plain value, like
`minecraft:glowstone_dust,16`
will make glowstone dust stack maximum at `16`

??
