### ISSUE TITLE
Minecraft crash report for 1.12.2, crash effecting this mod and another mod

### ISSUE THREAD

**Issue by Bakaistic** [Insane-96/IguanaTweaksReborn#181]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.12.2
* Forge: 14.23.5.2854
* IguanaTweaks Reborn: 1.5.2
* InsaneLib: ???

**What Happens**:  
Crashes apon initalization. Gives this screen: https://prnt.sc/1qkth4b. Modified pack of "Dimension Zero"

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://pastebin.com/rt6mmBVm

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
Unsure

**Comment by Insane96** [comment]
1.12 is no longer supported
