### ISSUE TITLE
Health Regen Presets besides IGUANA_TWEAKS Stops All Natural Health Regeneration

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Insane-96/IguanaTweaksReborn#182]
**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.2
* IguanaTweaks Reborn: 2.7.5-mc1.16.5
* InsaneLib: 1.1.2-mc1.16.5

**What Happens**:  
Adjusting anything in the [Hunger."Health Regen"] sub category stops health from regenerating naturally. The "Health Regen Preset" = "IGUANA_TWEAKS" preset is the only one that works as intended, selecting "NONE" or "COMBAT TEST" also stop vanilla health regeneration.  Even if I set the preset to "Health Regen Preset" = "NONE" and manually input the same values as are used for the Iguana Tweaks preset, natural regeneration still ceases to function. 

**Logs / Crash reports**: (Latest Log) https://gist.github.com/RobertHDPotatoes/64b4e37637d4fc96d2d922280f0145a1

**Config**:  https://pastebin.com/ARa1g8vY

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  Yes, it can be reproduced with only InsaneLib and IguanaTweaks Reborn installed. Simply install only those two mods, change "Health Regen Preset" = "IGUANA_TWEAKS" to "Health Regen Preset" = "NONE" and health will stop regenerating naturally, even with default settings which are supposed to be vanilla(?).

**Comment by Insane96** [comment]
I can tell you that Combat test works as I'm using it in a pack. For the NONE I need to check
