### ISSUE TITLE
Crash when using Astral Sorcery's Nocturnal Powder

### ISSUE THREAD

**Issue by IchHabeHunger54** [Insane-96/IguanaTweaksReborn#191]
**Versions**:
* Minecraft: 1.16.5
* Forge: 36.2.4
* IguanaTweaks Reborn: Alpha-2.8.0
* InsaneLib: 1.2.1

**What Happens**:
I used Astral Sorcery's Nocturnal Powder. Nocturnal Powder is an item that, when thrown, spawns a dark particle cloud at the impact point which spawns mobs inside. However, Iguana Tweaks seems to cause a crash.

**Logs / Crash reports**:
https://gist.github.com/IchHabeHunger54/d66f1209da59fc9dd25d1192540ab50e
Note that this is not the entire log, I had to cut some stuff at the top because Gist crashed upon uploading a 50MB log.

**Config**:  
https://gist.github.com/IchHabeHunger54/76ee382db31f6dd6f72a2da6f5d33dc4

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:
No, as it's a mod incompatibility

**Comment by Insane96** [comment]
For some reasons, they're spawning the mob as "From spawner", while it's not true. Thanks for the report.
