### ISSUE TITLE
In 1.16.5, using tags such as "#minecraft:logs,8" doesnt allow limiting all types of logs to 8 per stack

### ISSUE THREAD

**Issue by TacocaTYT** [Insane-96/IguanaTweaksReborn#194]
When trying to limit my carry size for stone, cobble, and log type blocks, using tags results in seemingly 0 changes. i set logs to 10 and stone and cobble tags to 5 but cobble is still stacking to 16

**Comment by TacocaTYT** [comment]
how can i fix this?

**Comment by Insane96** [comment]
Reopen the issue by following the "Bug Report" template
