### ISSUE TITLE
[Crash / 1.18] Disabling Protection enchantment with other mod makes game crash on startup.

### ISSUE THREAD

**Issue by KKotik** [Insane-96/IguanaTweaksReborn#208]
[crash-2022-01-31_16.41.26-client.txt](https://github.com/Insane96/IguanaTweaksReborn/files/7971115/crash-2022-01-31_16.41.26-client.txt)

**Comment by Insane96** [comment]
This is not a valid crash report. Please reopem following the issue template.

**Comment by KKotik** [comment]
Turned out that this is happening when combat section is disabled and protection is enabled.

**Comment by Insane96** [comment]
This is definitely strange as the module should still load.
