### ISSUE TITLE
[1.18 / CRASH] Startup crash related with combat module.

### ISSUE THREAD

**Issue by KKotik** [Insane-96/IguanaTweaksReborn#209]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.18.1
* Forge: 39.0.64
* IguanaTweaks Reborn: 2.9.1
* InsaneLib: 1.4.3

**What Happens**:  
My modpack crashing on startup.

//Please send logs even if you don't have any crash  
**Logs / Crash reports**:  
https://pastebin.com/XLK7dhgz

//If different from default
**Config**:  
https://pastebin.com/bJHpecUt

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
No

**Comment by KKotik** [comment]
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/7971458/latest.log)
[debug.log](https://github.com/Insane96/IguanaTweaksReborn/files/7971459/debug.log)

**Comment by Insane96** [comment]
You need to reproduce it with less mods.

**Comment by KKotik** [comment]
Might be got that. Making me disabling the mod forcing to get missing mods forge screen. And fixing that.

**Comment by KKotik** [comment]
Turns out to be issues with forge missing mod screen instead.
Got it fixed.

**Comment by Insane96** [comment]
How did you fix this?
