### ISSUE TITLE
Spawner Feature lag

### ISSUE THREAD

**Issue by someaddons** [Insane-96/IguanaTweaksReborn#211]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.28
* IguanaTweaks Reborn: 
IguanaTweaks Reborn 2.8.4
* InsaneLib: 
InsaneLib 1.4.2

**What Happens**:  
![image](https://user-images.githubusercontent.com/38401808/154670131-f319e28e-ca97-4bfb-b8d5-2153b8b87a48.png)
https://spark.lucko.me/dej8ACg8vw

The disabled temp-spawner module writes the spawners to NBT each tick, creating a bunch more lag than actually required.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/someaddons/9723609303d9ba7d46e60d88efc44da3

//If different from default
**Config**:  
https://gist.github.com/someaddons/cd59fa36107567c573fa706d556b577c

**Can be reproduced with a minimal set of mods? (E.g. IguanaTweaks Reborn + InsaneLib + Allurement) only?**:  
Yes/

**Comment by Insane96** [comment]
Thanks for the detailed report!

**Comment by someaddons** [comment]
sure :D btw one solution could be to add a boolean isCleanedUp into the mixin, then you'll just have to do it once per spawner
