### ISSUE TITLE
[1.18.1] Cow gets milked, milk is drinked even without right-clicking

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Insane-96/IguanaTweaksReborn#213]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.18.1
* Forge: 39.1.2
* IguanaTweaks Reborn: 2.9.2
* InsaneLib: 1.4.3

**What Happens**:  
Explain what's the problem
As explained in the title, when I milk a cow I get milk for a brief second and then it disappeared, meaning the milk bucket becomes a regular bucket again after milking.

https://user-images.githubusercontent.com/72312697/159139835-63a9ad36-6d60-4065-88db-ac507aa807ee.mp4

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/8310201/latest.log)

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG
[https://pastebin.com/Mn5vPFay](https://pastebin.com/Mn5vPFay)
**Can be reproduced with a minimal set of mods? (E.g. IguanaTweaks Reborn + InsaneLib + Allurement) only?**:  
Yes/No
Yes

**Comment by Insane96** [comment]
Reproduce it with a minimal set of mods.

**Comment by GeorgeOrwell1** [comment]
It can be reproduced using only IguanaTweaks and InsaneLib (on a brand new world):
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/8310870/latest.log)

**Comment by Insane96** [comment]
Can't reproduce it. Write the steps to reproduce it

**Comment by GeorgeOrwell1** [comment]
I mean if you have my config and versions for both Forge and Iguana Tweaks, the only thing left is to create a world and then milk a cow lol. If you want it in steps (for some reason), here you go:

1. Install the corresponding Forge, Iguana Tweaks and Insane Lib versions as well as my config.
2. Load up Minecraft and create a new world.
3. Grab a bucket and change game mode into survival then milk a cow with an empty bucket.
4. Watch how the milk dissapeares from the bucket.

**Comment by Insane96** [comment]
I did it, same config and version, only Iguana and Lib

**Comment by GeorgeOrwell1** [comment]
Then I don't know. Have you checked if there's something in the log? If you want I can try to provide with more files or information if it helps resolve the bug.

**Comment by Insane96** [comment]
Created a profile on Curseforge with the mentioned forge version
Added Iguana and Lib, same versions.
Created world, spawned cow, got bucket, the cow can be milked normally.

**Comment by GeorgeOrwell1** [comment]
Works perfectly fine without your mod:

https://user-images.githubusercontent.com/72312697/159168857-abe97af7-c68e-4627-a301-eaf5b7d83571.mp4

This is with your mod:

https://user-images.githubusercontent.com/72312697/159168992-35e21ad2-f314-494a-a5d1-4d26ce95012b.mp4

Also found that the milk only disappears if I have it in my hand, if I quickly scroll from the milk bottle it stays in my inventory (see second video). Your mod also seems to disable the milking sound for when you milk the cow.

**Comment by Insane96** [comment]
Seems like you drink the milk as soon as you milk the cow ... I really don't know how to fix this.

**Comment by Insane96** [comment]
Fixed for the next update, at the cost that the hand swings even if the cow's milk is not ready.
