### ISSUE TITLE
Crash with BrassAmber BattleTowers spawner

### ISSUE THREAD

**Issue by mosharky** [Insane-96/IguanaTweaksReborn#214]
**Versions**:
* Minecraft:  1.18.1
* Forge: 39.1.2
* IguanaTweaks Reborn: 2.9.2
* InsaneLib: 1.4.3

**What Happens**:  
The game crashed as soon as I teleported to a battle-tower from the [BrassAmber BattleTowers](https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers) mod

**Logs / Crash reports**:  
[Crash report](https://gnomebot.dev/paste/955330117679325184)
[latest.log](https://gnomebot.dev/paste/955329996233252924)

**[Config](https://gnomebot.dev/paste/955329474306658314)**

**Can be reproduced with a minimal set of mods? (E.g. IguanaTweaks Reborn + InsaneLib + Allurement) only?**:  
Yes, with just IguanaTweaks Reborn, InsaneLib, and BrassAmber BattleTowers

**Comment by Insane96** [comment]
~Logs are no longer available.~ The website is just down

**Comment by mosharky** [comment]
[Config](https://pastebin.com/Hr1b51bA)
[log](https://pastebin.com/9k9ngcbC)
[crash](https://pastebin.com/x33JSsNY)
