### ISSUE TITLE
Explosion Overhaul stops custom creeper explosion functionality from triggering

### ISSUE THREAD

**Issue by Dutchs** [Insane-96/IguanaTweaksReborn#216]
**Versions**:
* Minecraft: 1.18.2
* Forge: 40.0.52
* IguanaTweaks Reborn: 2.9.3
* InsaneLib: 1.4.6

**What Happens**:  
"Explosion Overhaul" breaks custom creeper explosion functionality, settings it to false will cause this functionality to start working again.
For instance a creeper which places blocks when it explodes, in the radius of the explosion.

I'm unable to give a link to said mod as its currently not publicly available, but the code which handles the custom creeper explosions looks like:
```java
@SubscribeEvent(priority = EventPriority.LOWEST)
public void boomEvent(ExplosionEvent.Start event) {
    if (!event.getWorld().isClientSide) {
        if (event.getExplosion().getExploder() instanceof EntityCustomCreeper) {
            EntityCustomCreeper creeper = (EntityCustomCreeper)event.getExplosion().getExploder();
            creeper.explodeCreeper();
            event.setCanceled(true);
        }
    }
}
```

One option that could work in this instance would be if there was a blacklist for entity id's which should not be handled by Explosion Overhaul.

**Can be reproduced with a minimal set of mods? (E.g. IguanaTweaks Reborn + InsaneLib + Allurement) only?**:  
Yes

**Comment by Insane96** [comment]
The problem here is that both the custom creeper and ITR use lowest priority. One fix would be to increase their priority to Low.

**Comment by Insane96** [comment]
Added a blacklist for the next update
