### ISSUE TITLE
Minor suggestion on weapon nerf tooltip

### ISSUE THREAD

**Issue by aghostofstarman255** [Insane-96/IguanaTweaksReborn#220]
Not sure how possible this is but for example instead of saying "-1 Attack Damage" it would just be "4 Attack Damage".
![2022-05-20](https://user-images.githubusercontent.com/79660102/169453232-16131f13-d7cc-4517-b78c-7101ba978d80.png)

**Comment by Insane96** [comment]
Not possible. Just how the attribute system works

**Comment by Insane96** [comment]
This has been fixed in Survival Reimagined
