### ISSUE TITLE
[1.12.2] Incompatibility with the mod "Berries And Mobs"

### ISSUE THREAD

**Issue by derplordofdeath** [Insane-96/IguanaTweaksReborn#221]
**Versions**:
* Minecraft: [1.12.2]
* Forge: [14.23.5.2859]
* IguanaTweaks Reborn: [IguanaTweaksReborn-1.5.1-mc1.12.x]
* InsaneLib: [N/A]

**What Happens**: The game crashes and I get an error that the cause is "IguanaTweaks Reborn" "Foam​Fix" and "Berries And Mobs" I know it isn't "Foam​Fix" because I've used that mod since my mod list was made with  "IguanaTweaks Reborn" (around 200 mods in) and i am certain it is "Berries And Mobs" because whenever i remove it it works perfectly fine. However if i disable the movement tweaks in the config it doesn't crash and i can play normally so it seems the movement section of the config conflicts with something in "Berries And Mobs"

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**: https://pastebin.com/nkA2Rzqz I've chosen to redact my mod list in the report but the mods that cause it are "Berries And Mobs" and "IguanaTweaks Reborn" hence you don't need all my other mods making them optional I've also done this on a brand new instance of 1.12.2 (same forge version) with only "IguanaTweaks Reborn" ["Foam​Fix" with and without] and "Berries And Mobs" installed and the results were the same thing and the only issue is with the movement section of the mod with default configs once you disable it its fine
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**: https://pastebin.com/VXD035SU im certain this doesnt matter but if you wanna reproduce this with the config be my guest however the only thing you need to change is the movement tab to true if you wanna crash
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**: No  
Yes/No

**Comment by derplordofdeath** [comment]
Can be reproduced with IguanaTweaks Reborn + InsaneLib only?:
Yes/No

define this question better cause the way I interpreted this is "can you do it with only my mod/mods installed?" and it could mean "are you sure this is my mod/mods doing this? and not another mod combination" in fact just add those as the questions  lmao XD

**Comment by Insane96** [comment]
1.12 is no longer receiving updates. 1.18 only

**Comment by derplordofdeath** [comment]
bro really? ok then wtf

**Comment by Insane96** [comment]
Why should I keep updating a version that hasn't been updated for years? Most people have moved to 1.16+ so I don't see the point.

**Comment by derplordofdeath** [comment]
I don't get why you wouldn't update a version that A LOT of people still use especially when 1.12.2 is THE go to modding version compared to any other version. I just don't see how taking an hour out of your day to make a small patch with another mod is such a severe thing that it shouldn't be done. also if a mod that backports new features to a specific version (1.12.2) that already should indicate that a lot of people still use 1.12.2.


I'm gonna go ask if the author of Berries And Mobs can fix this without you updating your mod. I just thought this would be your problem more than the other mods thanks for your time have a nice day

**Comment by Insane96** [comment]
> taking an hour out of your day

If only
