### ISSUE TITLE
Add option to only disable FoV changes for Iguana Tweaks' mechanics

### ISSUE THREAD

**Issue by Spleenczar** [Insane-96/IguanaTweaksReborn#222]
Request: Add option to disable FoV changing specifically due to Iguana Tweaks' movement mechanics, including equipment weight, tagging, terrain slowdown, and backing up. Ideally would be toggleable for each one depending on player preference.

Not sure if this is feasible to implement, but I assume it's possible because of how Soul Sand works with slowing you down and not changing it (and I could've sworn I've seen mods do this before). Many players including myself like sprinting and other vanilla functions changing the FoV, but the FoV changing constantly while running across terrain and any time you back up with this mod is extremely annoying. Since the vanilla option to disable dynamic FoV turns _everything_ off, that's not really a helpful setting in this case.

**Comment by Insane96** [comment]
That's a pain to do, not gonna get into it again. Disable all the fov changes in video settings
