### ISSUE TITLE
[1.18.2] Cannot invoke "net.minecraft.world.food.FoodProperties.m_38744_()" because the return value of "net.minecraft.world.item.Item.m_41473_()" is null (crash on startup)

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Insane-96/IguanaTweaksReborn#226]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.18.2
* Forge: 40.1.51
* IguanaTweaks Reborn: 2.11.3
* InsaneLib: 1.5.0

**What Happens**:  
Explain what's the problem
When I load the game with Iguana tweaks, this crash comes up (probably a conflict with another mod). In the crash reports there are mentions of "at insane96mcp.iguanatweaksreborn.module.stacksize.feature.GeneralStacking.processFoodStackSizes" so I figured it has to do with your mod. **For some reason, it works if you revert to version 2.11.2 of Iguana Tweaks on client. On server, the issue seems to still be there.**
_(Edit: I've updated Iguana Tweaks and Insane Lib to their latest versions (2.11.4 and 1,5.1) but the issue persists.)_

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
[crash-2022-06-14_14.40.07-client.txt](https://github.com/Insane96/IguanaTweaksReborn/files/8899836/crash-2022-06-14_14.40.07-client.txt)
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/8899838/latest.log)

//If different from default
**Config**:  [https://pastebin.com/Q3fCkx9S](https://pastebin.com/Q3fCkx9S)
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
Yes/No
**No**

**Comment by Insane96** [comment]
> Can be reproduced with IguanaTweaks Reborn + InsaneLib only?:
> Yes/No
> No

This means that you should try to reproduce with as less mods as possible.

Try to find out which food mod is giving that problem

**Comment by GeorgeOrwell1** [comment]
I think I've been able to locate the conflict; **it seems to be the [immersive weathering mod ](https://github.com/AstralOrdana/Immersive-Weathering) conflicting with your mod**. If I only have the immersive Weathering mod, there doesn't seem to be an issue and same goes if I only have Iguana Tweaks installed. However, if I have them both, a crash on startup appears saying that: "Cannot invoke "net.minecraft.world.food.FoodProperties.m_38744_()" because the return value of "net.minecraft.world.item.Item.m_41473_()" is null". I can make an issue on Immersie Weatherings Github and make a reference to this issue if that is needed.

**Comment by Insane96** [comment]
Yep, do it. I think I'm doing everything properly: check if it's edible and get the FoodProperies

**Comment by Insane96** [comment]
Could you test with latest versions? I don't get the crash in the dev environment.

EDIT: tested in a normal instance too. I get no crashes.

**Comment by Insane96** [comment]
Also updated Forge to .51

InsaneLib 1.5.1
IguanaTweaks Reborn 2.11.6
Immersive Weathering 1.2.11

**Comment by Insane96** [comment]
No updates from both other mod and you. Closing
