### ISSUE TITLE
[Suggestion] Vanilla Tweaks Datapack Automatic Loading

### ISSUE THREAD

**Issue by Darkosto** [Insane-96/IguanaTweaksReborn#228]
Hello!

I currently have trouble setting up a modpack using this mod due to the Vanilla Tweaks datapack turning on automatically. In doing so, it enables itself at the end of the datapack list and overrides any changes that I have made (for example, vanilla stone loot tables). My concern is that I would have to ask players to open the Datapack GUI when creating a new world and then close it so the Vanilla Tweaks datapack does not get loaded on world creation. I have looked through the configs, and cannot find a way to disable the automatic loading of this datapack in an effort to provide customized configs for players. The other concern this presents is overriding progression changes which will render much of my work bypassed when you get resources earlier than intended. 

Could we please have the option to opt-in rather than an opt-out feature? 

Thanks so much!

IguanaTweaksReborn: 2.11.6-mc1.18.2
MC: 1.18.2
Forge: 40.1.52

**Comment by Insane96** [comment]
I won't disable the automatic load of the datapack as otherwise it will never be used.

I'm going to add some kind of config option (if possible) to make it not enable automatically. If not possible I will make it opt-in.

**Comment by Insane96** [comment]
Doing some testing. How did you change the stone drops? Via mods like OpenLoader?

**Comment by Insane96** [comment]
I'm investigating this as when using datapacks or mods like openloader, the loot tables from the integrated datapacks should not override them.

In the meantime I'm going to release a new version disabling them.

**Comment by Darkosto** [comment]
Currently I use this mod to automatically load in datapacks from a folder in the minecraft root folder: https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack

The benefit is not having to ask players to load up datapacks each new world and it loads them last on the list in most cases. This is how I am able to override vanilla features like the stone loot table. The issue with Iguana Tweaks is your datapack entry is loaded after mine so it will override any changes I make.

**Comment by Insane96** [comment]
~I~ Silk might have found a way to make integrated datapacks not override world's datapacks. Needs to be tested.

![image](https://user-images.githubusercontent.com/7185104/183884715-68eb2bfb-6680-44d7-9e46-800a703b65a0.png)

**Comment by Insane96** [comment]
This will finally be fixed in 1.19.4 where you'll be able to use config to disable the datapacks.

**Comment by Insane96** [comment]
This has been fixed in Survival Reimagined
