### ISSUE TITLE
[1.16.5] Crashing on world Boot - Exception in server tick loop

### ISSUE THREAD

**Issue by Nero15739** [Insane-96/IguanaTweaksReborn#229]
I've tried to use this mod and It is crashing anytime I attempt to load into a world. I have narrowed it down to this mod so it certainly is the culprit as disabling it stops any crashing.
I've Attached the crash log file here, I hope it helps.
[crash-2022-07-16_22.02.18-server.txt](https://github.com/Insane96/IguanaTweaksReborn/files/9125802/crash-2022-07-16_22.02.18-server.txt)

**Comment by Nero15739** [comment]
I have Just Disabled any other mods and It appears this is not happening on it's own.
I have done some quick testing and the other mod which could be interacting with this is one of these mods in here.
[crash-2022-07-16_23.30.27-server.txt](https://github.com/Insane96/IguanaTweaksReborn/files/9125889/crash-2022-07-16_23.30.27-server.txt)

**Comment by Nero15739** [comment]
So When these two mods are enabled the game crashes when loading a world. 
|IguanaTweaks Reborn           |iguanatweaksreborn            |2.8.5
|Lava Monster                  |lava_monster                  |1.0.9 

I'm not sure why this is occurring but there you go 
[crash-2022-07-16_23.39.34-server.txt](https://github.com/Insane96/IguanaTweaksReborn/files/9125913/crash-2022-07-16_23.39.34-server.txt)

**Comment by Insane96** [comment]
Report to them. Seems like they're spawning via spawner without a SpawnReason.
Also you should have used the issue template...

**Comment by Insane96** [comment]
No more replies in a month, closing.
