### ISSUE TITLE
Armor Speed Debuff Persists in Creative Mode

### ISSUE THREAD

**Issue by Darkosto** [Insane-96/IguanaTweaksReborn#231]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.18.2
* Forge: 40.1.73
* IguanaTweaks Reborn: 2.12.0
* InsaneLib: 1.5.1

**What Happens**:  
I believe the speed debuff while wearing armor affects the player while in creative mode. It would be convenient if the debuff did not apply while in creative so testing could be a bit easier.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

![image](https://user-images.githubusercontent.com/10309699/184444520-e093e6b3-c973-4939-ad0a-9dfd46c38a7f.png)

**Comment by Insane96** [comment]
The speed debuf is an attribute modifier. As such can't really be prevented in creative.

**Comment by Darkosto** [comment]
Ah! that's unfortunate, thanks for looking into it!
