### ISSUE TITLE
Add a chance for animals to consume breeding material without "falling in love"

### ISSUE THREAD

**Issue by cocojiang39** [Insane-96/IguanaTweaksReborn#232]
// Here your suggestion
I love this mod so much, it makes my game more balanced and makes my nonprofit community servers more difficult and fun, thank you so much.

But I found a problem that if I simply make the animals grow and reproduce for a longer time, the player will tame a lot of animals to expand, which is extremely laggy and unscientific (because breeding has almost no consumption), so I hope you can come up with one The function is to turn the food that the animals need to consume into an adjustable item

**Comment by Insane96** [comment]
This is pretty confusing. Could you elaborate more?

**Comment by Insane96** [comment]
I guess that's what you want

**Comment by Insane96** [comment]
Sadly that's not possible
