### ISSUE TITLE
Stack Size restart bug

### ISSUE THREAD

**Issue by Izre** [Insane-96/IguanaTweaksReborn#237]
Versions:
Minecraft:  1.18.2
Forge:  40.1.80
IguanaTweaks Reborn: 2.12.7
InsaneLib:  1.5.1

In folder config I changed the file: iguanatweaksreborn-common.toml
In category ["Stack Size"] i changed these settings:
"Food Stack Multiplier" = 0.5
"Item Stack Multiplier" = 0.5
"Block Stack Reduction" = true
"Block Stack Multiplier" = 0.5

When you enter the game or restart it. you create a world or enter it
We see one of 3 different stack size patterns:
1) 1/4 of the stack size, example: stick=16
2) 1/8 of the stack size, example: stick=8
2) everything stacks one by one, example: stick=1
This is a serious problem that has existed for half a year, it didn’t happen on older versions before

Install only two mods: IguanaTweaks Reborn and InsaneLib

**Comment by Insane96** [comment]
~I need your config~ I'm stupid

> This is a serious problem that has existed for half a year, it didn’t happen on older versions before  

And yet no one thought about opening an issue here so I can check it
