### ISSUE TITLE
Ignoring terrain slowdown config

### ISSUE THREAD

**Issue by Proxwian** [Insane-96/IguanaTweaksReborn#240]
**Versions**:
* Minecraft:  1.18.2
* Forge: 40.1.84
* IguanaTweaks Reborn: 2.12.8

**What Happens**:  
Mod ignores config parameter terrain slowdown when set to false, it still read values from Material On Slowdown, Material In Slowdown, Custom Terrain slowdown parameters

**Comment by Insane96** [comment]
There's a reason why the issue template asks for the config file ... I need it

**Comment by Insane96** [comment]
Tested in both 1.18 and 1.19 and it works properly

**Comment by Proxwian** [comment]
https://pastebin.com/PuZ1ezua

**Comment by Insane96** [comment]
Still can't reproduce with that config. Both 1.18 and 1.19
