### ISSUE TITLE
FOV twitches when standing on terrain speed changing block

### ISSUE THREAD

**Issue by Proxwian** [Insane-96/IguanaTweaksReborn#241]
**Versions**:
* Minecraft:  1.18.2
* Forge: 40.1.84
* IguanaTweaks Reborn: 2.12.8

**What Happens**:  
When player standing on block that have terrain slowdown parameter (contains in Material On/In Slowdown list), player FOV starts to twitch, which is very annoying

**Comment by Insane96** [comment]
Disable FOV changes from the video settings. There's nothing I can do
