### ISSUE TITLE
[1.18.2]Crash with BrassAmber BattleTowers mod's spawner

### ISSUE THREAD

**Issue by Greygreygod** [Insane-96/IguanaTweaksReborn#242]
Mod version:IguanaTweaksReborn-2.12.8-mc1.18.2,BrassAmberBattleTowers-1.18.2-2.3.1
The funtion "Enable Temporary Spawners" will crash the game when i use with BrassAmber BattleTowers mod.After i turn off the funtion,it can be continue.
[crash-2022-12-18_01.42.58-server.txt](https://github.com/Insane96/IguanaTweaksReborn/files/10252318/crash-2022-12-18_01.42.58-server.txt)

**Comment by Insane96** [comment]
Update IguanaTweaks, you're using a reaaaaally old version

**Comment by Greygreygod** [comment]
But it is the latest version about minecraft version 1.18.2 in curseforge page,where can i download more latest?

**Comment by Insane96** [comment]
Sorry, I've read the battletowers' mod version. I'll take a look at it.

**Comment by Insane96** [comment]
BTW Quite sure BattleTowers is doing something wrong on their side, as a spawner is not a spawner

**Comment by Insane96** [comment]
Fixed in 2.12.9
