### ISSUE TITLE
Item (Gear) Properties/Attributes, like additional Toughness, don't Stack; they Overwrite with whatever you put on last

### ISSUE THREAD

**Issue by Reshirou** [Insane-96/IguanaTweaksReborn#243]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.19.2
* Forge: 43.2.1
* IguanaTweaks Reborn: 2.13.4
* InsaneLib: 1.7.2

**What Happens**:  
With nothing but IguanaTweaks Reborn and InsaneLib, and with the unmodified auto generated configs, the additional armor points from Netherite and the additional Toughness from Iron don't work correctly. One modified gear type applies its change properly, but if you put on another, the additional Toughness/Armor from the previous gear reverts to vanilla and you only get the benefit from the latest piece of gear. This happens with literally nothing but ITR and IL, but after confirming that much I did install Armor Points ++ to easily see the Toughness.

For instance:
Put on Iron Boots,
Expected Result: 1 Total Toughness
Result: 1 Total Toughness

Now put on Iron Leggings
Expected Result: 2 Total Toughness
Result: 1 Total Toughness

Now take off just the Leggings OR the Boots
Expected Result: 1 Total Toughness
Result: 0 Total Toughness

**Comment by Insane96** [comment]
That's not possible. The attributes are just like vanilla, I don't change that behaviour, I just add the attribute modifiers, unless ...

**Comment by Insane96** [comment]
Yep, confirmed, they have all the same UUID so they don't stack ...

**Comment by Reshirou** [comment]
Thanks for looking into/fixing this, it's one of my favorite features of IguanaTweaks Reborn.

**Comment by Insane96** [comment]
Fixed in 2.13.5
