### ISSUE TITLE
item_modifiers aren't shown client side when on a server.

### ISSUE THREAD

**Issue by Reshirou** [Insane-96/IguanaTweaksReborn#246]
here is a log of the server starting up; I CTRL F'd IguanaTweaks to see if I could find the issue on my end, but I couldnt
https://paste.shockbyte.com/udividufiyejegisapug

here is a zip of my config files; theyre configured with a lot of mod added gear
[iguanatweaksreborn.zip](https://github.com/Insane96/IguanaTweaksReborn/files/10528400/iguanatweaksreborn.zip)

**Comment by Reshirou** [comment]
UPDATE: by equipping an extra health giving armor, it's become clear the problem is actually a visual issue

The gear all does indeed have attributes applied, you just cant see what those stats are when joining a server, even with synced configs

**Comment by Insane96** [comment]
Could you elaborate more on the issue? Just tested on server and it works properly.

**Comment by Insane96** [comment]
The client seems to use the cached client side data.

**Comment by Insane96** [comment]
This has been fixed in Survival Reimagined.
