### ISSUE TITLE
IguanaTweaks Reborn 2.8.6 Crash - Rendering overlay - MC 1.16.5 Forge 36.2.39

### ISSUE THREAD

**Issue by JNCHGTR** [Insane-96/IguanaTweaksReborn#247]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**: 
* Minecraft: 1.16.5
* Forge: 36.2.39
* IguanaTweaks Reborn: IguanaTweaksReborn-2.8.5
* InsaneLib: InsaneLib-1.4.2

**What Happens**:  
Explain what's the problem

Working on my custom mudpack (Fantasia Adventures) I have been using IguanaTweaks for a while but today, as I was customizing some BYG textures to add to my custom texture pack I opened the game like normal, no issues, then I added some PNGs to my texture pack folder, closed the game, re-opened it and I consistently get a crash when trying to load up the main menu. Basically launch Minecraft, wait on the red screen loading with the Mojang logo then the game crashes:

Crash report (gist): https://gist.github.com/JNCHGTR/9389623a75c966b3cbd65152afcb0077
Latest.log (gist): https://gist.github.com/JNCHGTR/3fa23edbcd9d942e1c0abb8e22de59ef

//If different from default
**Config**: https://gist.github.com/JNCHGTR/e54b3dd412e7678b25a379901151ac0d

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
No

If your answer to the previous question is No, then go do it. If doesn't happen with the mod alone, then try to narrow down the mod conflict.

**Comment by Insane96** [comment]
This is not an IguanaTweaks problem

The crash mentions betteranimationscollection
