### ISSUE TITLE
Spawner Feature Lag

### ISSUE THREAD

**Issue by someaddons** [Insane-96/IguanaTweaksReborn#249]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**: IguanaTweaksReborn-2.13.5-mc1.19.2
* Minecraft:  1.19.2
* Forge: 
* IguanaTweaks Reborn:  IguanaTweaksReborn-2.13.5-mc1.19.2
* InsaneLib: InsaneLib-1.7.5-mc1.19.2

**What Happens**:  
The temp spawner feature creates additional lag despite being disable in the config file.
![image](https://user-images.githubusercontent.com/38401808/227905169-7d160f6a-eeef-4f8c-9e4c-da04d4075bb4.png)

Both servertick and client tick hooks are still active with the feature disabled:
https://github.com/Insane96/IguanaTweaksReborn/blob/bece6f170d59c0fb0569a946472b4effaa0d9e0d/src/main/java/insane96mcp/iguanatweaksreborn/module/misc/feature/TempSpawner.java#L106
https://github.com/Insane96/IguanaTweaksReborn/blob/bece6f170d59c0fb0569a946472b4effaa0d9e0d/src/main/java/insane96mcp/iguanatweaksreborn/module/misc/feature/TempSpawner.java#L127

I'd suggest they simply do nothing when the temp spawner feature is disabled in the config.
 The expensive/laggy call they're using here is in its `ìsDisabled` check, which writes all the spawners data into nbt to then check the data each tick.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
This has been addressed in 2.13.6
Many performance improvements have been made (e.g. spawners no longer ticks when disabled)
