### ISSUE TITLE
Incompatibility with FTB Chunks explosion protection

### ISSUE THREAD

**Issue by desht** [Insane-96/IguanaTweaksReborn#250]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.19.2
* Forge: 43.2.8
* IguanaTweaks Reborn: 2.13.6
* InsaneLib: (not sure, and not important)

**What Happens**:  
The explosion overhaul feature in IT Reborn breaks FTB Chunks explosion protection. FTB Chunks works by removing protected blocks from the `Explosion#toBlow` list, but from my perusal of the source code for IT Reborn (`ITExplosion#gatherAffectedBlocks`), it does its own calculation of which blocks should be affected, basically negating any attempt by mods to protect blocks. It should honour the value of the `Explosion#getToBlow()` method.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
n/a
//If different from default
**Config**:  
n/a

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
I'll see what I can do

**Comment by Insane96** [comment]
Does this still happen in the latest version?

**Comment by Insane96** [comment]
Closed as stale
