### ISSUE TITLE
On the issue of mining time

### ISSUE THREAD

**Issue by Windavilin** [Insane-96/IguanaTweaksReborn#252]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.19.2
* Forge: 43.2.21
* IguanaTweaks Reborn: 2.13.6
* InsaneLib:1.7.5

**What Happens**:  
I adjusted the excavation time of the blocks. In offline mode, it works well, but on the server, I found that it is often misjudged as a block that has a mining time of the original version but needs to wait for a period of time, like this

https://github.com/Insane96/SurvivalReimagined/assets/141706381/544250ec-1e86-4d28-9f46-11ceb772c4c1

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
[latest.zip](https://github.com/Insane96/SurvivalReimagined/files/12309504/latest.zip)
//If different from default
**Config**:  
[iguanatweaksreborn.zip](https://github.com/Insane96/SurvivalReimagined/files/12309508/iguanatweaksreborn.zip)
**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
No

**Comment by Insane96** [comment]
This has been fixed in SurvivalReimagined. In IguanaTweaks reborn, make sure client and server have the same config.

**Comment by Windavilin** [comment]
I restarted the server and tried again, but found that the situation remained the same

This is the running log of the server. I only recorded the test results of digging a few blocks after I died twice
[latest.log](https://github.com/Insane96/SurvivalReimagined/files/12312237/latest.log)
