### ISSUE TITLE
On the issue of mining time II

### ISSUE THREAD

**Issue by Windavilin** [Insane-96/IguanaTweaksReborn#253]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.19.2
* Forge: 43.2.21
* IguanaTweaks Reborn: 2.13.6
* InsaneLib: 1.7.5

**What Happens**:  
Thank you for informing me. But after confirming the consistency of the configuration files between the client and server based on your suggestion, I found the following phenomenon:

The hardness configuration of the blocks in custom_ hardnesses.json is working properly, but other blocks still have the same situation as before.

like this:

https://github.com/Insane96/SurvivalReimagined/assets/141706381/73dabc9e-6855-43f7-ae1a-bad8a3fba7c6

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
No

**Comment by Insane96** [comment]
Try restarting the game and entering the server without joining sp first

**Comment by Windavilin** [comment]
I restarted the server and tried according to your suggestion, but found that the situation remained the same
This is the running log of the server. I only recorded the test results of digging a few blocks after I died twice
[latest.log](https://github.com/Insane96/SurvivalReimagined/files/12312237/latest.log)

**Comment by Insane96** [comment]
Did you restartc the game and joined the server first?

**Comment by Windavilin** [comment]
Yes, and before entering the single player game, I entered the server first

**Comment by Windavilin** [comment]
According to your statement, I should do it this way, right？
[bug_3.zip](https://github.com/Insane96/SurvivalReimagined/files/12313092/bug_3.zip)

**Comment by Insane96** [comment]
Quite strange

**Comment by Insane96** [comment]
But this will never be fixed, sorry, 1.19.2 is no longer supported, and even it was, this fix would require a huge effort, that I already did for Survival Reimagined. Disable the global hardness feature.

Also double check the global hardness multipliers and dimension multiplier are the same client and server.

**Comment by Windavilin** [comment]
okay.thank you all the same
