### ISSUE TITLE
Add the ability to turn off/move the tiredness bar.

### ISSUE THREAD

**Issue by jaimarl** [Insane-96/IguanaTweaksReborn#254]
Add the ability to move the fatigue bar and invert the fill side of the bar.

**Comment by Insane96** [comment]
This can already be done in the config, and in later versions the bar is already removed

**Comment by Jaimarl** [comment]
On the latest 1.18.2 version, the bar is still here.

**Comment by jaimarl** [comment]
> This can already be done in the config, and in later versions the bar is already removed

On the latest 1.18.2 version, the bar is still here.

**Comment by Insane96** [comment]
Oh, that was added in 1.19.2
