### ISSUE TITLE
 Cannot set property PropertyDirection 1.12.2 incompatible mods:BYG(leafpile),futuremc,future-versions(cartographytable)

### ISSUE THREAD

**Issue by SoimuBadass** [Insane-96/IguanaTweaksReborn#255]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  
* Forge: 
* IguanaTweaks Reborn: 
* InsaneLib: 

**What Happens**:  
Explain what's the problem

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes/No

**Comment by Insane96** [comment]
1.12.2 is no longer supported
