### ISSUE TITLE
[Bug] Possible issue with durability syncing

### ISSUE THREAD

**Issue by Maypul** [Insane-96/IguanaTweaksReborn#256]
**Versions**:
* Minecraft:  1.19.2
* Forge: 43.2.21
* IguanaTweaks Reborn: 2.13.6
* InsaneLib: 1.7.5

**What Happens**:  
I am changing some durability of tools using tool_durabilities.json, I have DurabilityTooltip mod that shows durability of tools (also raised an issure here: https://github.com/SuperMartijn642/DurabilityTooltip/issues/13).
But sometimes, I can not really consistently reproduce it, durability shows as default, before the change but it still breaks after X hit I set in IguanaTweaks. SuperMartijn642 mentioned it might be because IguanaTweaks might not be syncing it correctly.
Usually it is noticeable after random server reboot where it shows wrong value.

As a side note, when setting stack size with IguanaTweaks, some of my players noticed it let them stack bigger size, and then instantly it corrects itself to correct stack size (visual thing)

**Logs / Crash reports**:  
https://pastebin.com/RCXCVwXn
No crashes, no logs when it happened, mod list might be slightly different as it's taken from one zipped logs and I can't really know which log would be where it happened.
Also client/server modlist: https://pastebin.com/EsMQnjs9

**Config**:  
https://pastebin.com/KBU4JiEL

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
It cannot be consistently reproduced.

**Comment by Insane96** [comment]
This has been fixed in Survival Reimagined

**Comment by Maypul** [comment]
@Insane96 Is there any possibility to bring these bugfixes to 1.19.2? I have downloaded newest version from the Survival Reimagined page, but 1.19.2 appears to have only ITR version.

**Comment by Insane96** [comment]
No sorry, this would require a huge amount of effort.

**Comment by Maypul** [comment]
It's quite unfortunate but understanable. Could you confirm which sections of mod have this bug or is it only stacks and durability so I could disable them.

**Comment by Insane96** [comment]
Tecnically anything json driven. So custom stack, durability, mining speeds

**Comment by Maypul** [comment]
Thank you for your help, I think I will be able to move most of what I use to KubeJS or just use global modifier (in-mod, ignoring json files), though it seems that Food & Drinks section might be also affected (1.19.2). As it uses formula to calculate for hunger/saturation values, mods like Apple Skin still show max or original value before calculations.
