### ISSUE TITLE
Duplicate "Plants Growth Multiplier" Variable in Config

### ISSUE THREAD

**Issue by Lonemind** [Insane-96/IguanaTweaksReborn#258]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.18.2
* Forge: 40.2.14
* IguanaTweaks Reborn: 2.12.12
* InsaneLib: 1.5.3

**What Happens**:  
In the config under the ["Sleep & Respawn".Tiredness] section there is a duplicate "Plants Growth Multiplier". I suspect you meant to put a variable related to listing out items that give the player Energy Boost. I do not use this feature so I did not do any testing, I just noticed it and thought it was likely a typo. Cheers!

**Comment by Insane96** [comment]
So minor I'm not gonna fix that
