### ISSUE TITLE
More sleep configs

### ISSUE THREAD

**Issue by Dune-Jumper** [Insane-96/IguanaTweaksReborn#26]
If I remember correctly, in the original Iguana Tweaks there was a config to set a cooldown for sleeping after placing a bed. Like if you placed a bed, you'd have to wait a day before you could sleep in it. It was useful for encouraging player to place beds in protected areas, instead of plopping them in the middle of the open and just skipping nighttime instantly.

**Comment by Insane-96** [comment]
> in the original Iguana Tweaks there was a config to set a cooldown for sleeping after placing a bed
Nope there wasn't
But I might come up with something good

**Comment by Dune-Jumper** [comment]
Huh, I could've sworn there was. Guess I have it confused with another mod.

**Comment by Insane-96** [comment]
Reopened here: https://github.com/Insane-96/IguanaTweaksReborn/issues/30
