### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#260]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.19
* IguanaTweaks Reborn: 3.0.2
* InsaneLib: 1.12.1

**What Happens**:  
Explain what's the problem
The game crashes upon startup. 

**Logs / Crash reports**:  
https://gist.github.com/CraftyZombie/aab161a293bed48c3e6f389251098f69 (latest.log and the Crash Report)

//If different from default
**Config**:  
(https://gist.github.com/CraftyZombie/f7b664fefc193815569fd2a9995718f8) (Also crashes when config is not modified.)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
No

**Comment by Insane96** [comment]
Send the `debug.log` pls

**Comment by CraftyZombie** [comment]
Here it is.
https://gist.github.com/CraftyZombie/8ec9a324a67e4f903f58c1bd780c968f

**Comment by Insane96** [comment]
There's a mod that's probably conflicting with the Music Mixin.
> **Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?:**
> No

This means you have to reproduce it with a minimal set of mods.

**Comment by CraftyZombie** [comment]
I don't understand why the Music Mixin still runs when I disabled it in the config?

However I will do my best to find the issue.

**Comment by CraftyZombie** [comment]
Apologies, upon updating my other mods, it seems the issue is resolved. I still have no idea what mod caused this, but if it's patched on the other end now, I suppose it's nothing to worry about.

Thank you for your time.

**Comment by Insane96** [comment]
> I don't understand why the Music Mixin still runs when I disabled it in the config?

The Mixin is still there even if it's disabled.

Well nice that some other mod fixed the issue.
