### ISSUE TITLE
[1.20.1] Crash With Immersive Engineering

### ISSUE THREAD

**Issue by Mike-U5** [Insane-96/IguanaTweaksReborn#262]
**Versions**:
* Minecraft:  20.1
* NeoForge: 47.1.84 
* IguanaTweaks Reborn: 3.0.4
* InsaneLib: 1.12.1

**What Happens**:  
The game crashes when I change any config option. (Presumably, I did not try with every single option but I tried several random ones and it crashes)

**Crashlog**:
https://gist.github.com/Mike-U5/6190e0e05381d8bd37d4d081e449efe1

**Config**:  
https://gist.github.com/Mike-U5/df3263960f79ec242f89015612f0e122

**Can be reproduced with a minimal set of mods?
IguanaTweaks Reborn + InsaneLib + MaxHealthFix + ImmersiveEngineering

**Comment by Insane96** [comment]
Did you report this to Immersive Engineering too? There's nowhere in the crashlog mentioning ITR

**Comment by CraftyZombie** [comment]
I was experiencing this issue a little while ago. ITR certainly has _something_ to do with it.

Deleting your IguanaTweaksReborn configs seems to work. It might be related to specific config options because after resetting my config, I've modified a fair number of things and no longer get the crash.

**Comment by Mike-U5** [comment]
@Insane96 I have opened an issue on the IE github too. But it is as @CraftyZombie says, it seems to happen with specific configuration options of ITR. Can't quite pin down which.

**Comment by Insane96** [comment]
I have no idea what might be causing this.

**Comment by JessAlias** [comment]
I'm experiencing the exact same error. The error only appears if Immersive Engineering is loaded, and if I disable ANY of the Data Pack mod settings that change recipes etc. So if I turn off "Hardcore Torches", the game crashes when trying to load a world. I can modify other settings, it's just the Data Packs that make the game explode when trying to load a world.

I'm going to go play with the config file for Immersive Engineering. Curious if there's something I can change there that will let me disable data packs. I'm guessing it has something to do with a recipe?

EDIT: Looking at the log file, the crash report mentions something about arc furnace recycling. I scanned through the IE config file, and saw this: 

		#The recycling functionality of the arc furnace is no longer controlled by a config option.
		#Like all IE recipes, this is now controlled via a datapack, using the recipe file:
		#immersiveengineering/recipes/arc_recycling_list.json

I'm no minecraft modder, but I'm guessing something isn't playing nicely here with the arc furnace recycling data pack.

**Comment by Insane96** [comment]
What's in that json?

**Comment by NotTohm** [comment]
same but its when i disable the nether roof

**Comment by Insane96** [comment]
So you disable *only* the Nether Roof data pack and the game crashes with IE?

**Comment by NotTohm** [comment]
yep

**Comment by Insane96** [comment]
I have no clue why a data pack that changes the Nether dimension could crash IE

**Comment by Insane96** [comment]
Does this still happen?

**Comment by Insane96** [comment]
closing as stale
