### ISSUE TITLE
Сrash on client startup 1.20.1

### ISSUE THREAD

**Issue by Kepyka** [Insane-96/IguanaTweaksReborn#263]
Hi!
Versions:
-Minecraft: 1.20.1
-Forge: 47.2.20
-IguanaTweaks Reborn: 3.0.5
-InsaneLib: 1.12.1
no other mods

I tried neoforge 47.1.88 and different versions of forge but the result is the same.
Help me please)

crash-report
https://gist.github.com/Kepyka/d20214800e0d006f53a7313e543a4732

**Comment by Insane96** [comment]
Send the full log. You're probably missing MaxHealthFix

**Comment by Kepyka** [comment]
Yes, MaxHealthFix was missing, everything worked, thanks
