### ISSUE TITLE
World load crash if Wandering Trades is disabled or files in the Wandering Trades folder is empty

### ISSUE THREAD

**Issue by NeuTraLZero** [Insane-96/IguanaTweaksReborn#265]
**Versions**:
* Minecraft: 1.20.1
* Forge: 47.2.6
* IguanaTweaks Reborn: 3.1.13
* InsaneLib: 1.12.1

**What Happens**:  
Title. The game will get stuck in a blank screen after "Reading world data" without going into the chunk loading screen

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/NeuTraLZero/399a97ce466c71a185a6647b71d6f006

//If different from default
**Config**:  
https://gist.github.com/NeuTraLZero/68c334b14b960f2d238f7481082ccb98

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes, but on minimal setup, the world will crash when interacting with a Wandering Trader instead of on world load

**Comment by Insane96** [comment]
Please reproduce this with ITR only and send the logs

**Comment by NeuTraLZero** [comment]
> Please reproduce this with ITR only and send the logs

https://gist.github.com/NeuTraLZero/ddcf9c9a0123810db08cabebb30fba49

**Comment by Insane96** [comment]
Fixed for next update, no need to mess with the file, just disable the feature
