### ISSUE TITLE
Suggestion, flinch-less damage

### ISSUE THREAD

**Issue by HiggsBonbon** [Insane-96/IguanaTweaksReborn#27]
An option to remove the flinch effect from damage over time effects like fire, poison and wither, because when you get 'hit' it screws with your momentum (and the camera).

**Comment by Insane-96** [comment]
I'll may remove not phisical damage from the "stun" effect

**Comment by Insane-96** [comment]
>  Nope, it still cancels your momentum, which can screw up jumps and incrementally slow you down. Plus there's the annoying sound, and the screen turning like ten degrees every single hit.

Closing for not reproducible behaviour
