### ISSUE TITLE
Disabling Unbreaking Items Continues to Prevent Modded Tools from Breaking

### ISSUE THREAD

**Issue by Lonemind** [Insane-96/IguanaTweaksReborn#270]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.2.1
* InsaneLib: 1.12.1

**What Happens**:  
It appears that enabling `Item Stats` makes all modded durability items unbreakable even when `Unbreakable Items` or `Unbreakable Enchanted Items` is disabled. Disabling those two options does indeed allow vanilla tools to break but not modded tools.
If I disable `Item Stats` entirely then modded tools can once again break.

**Logs / Crash reports**:  
https://mclo.gs/eHDKLty

**Config**:  
https://mclo.gs/dWxrRNh

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
> Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?:
> Yes

Well no, from the logs there are many more mods installed. Re-test with the least amount of mods

**Comment by Lonemind** [comment]
After some more testing I've found that no tools, not even vanilla tools, break when `Item Stats` is set to true while `Unbreakable Items` and `Unbreakable Enchanted Items` are set to false, unless those tools are listed in not_unbreakable.json.

Here's a debug.log from a test with just four mods and a config set up so that you can just plug it in to experience the problem.

Debug.log
https://mclo.gs/WxtH02H

Config
https://mclo.gs/JzOzfBz

**Comment by Insane96** [comment]
Could you test with latest version?

**Comment by Lonemind** [comment]
That seems to have fixed the issue. Thank you Insane.
