### ISSUE TITLE
[Suggestion] Tag/Configuration for Hardcore Portals

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#272]
// Here your suggestion
I think it would be cool if the adjustment in ITR that requires golden blocks/crying obsidian in Nether portal corners was configurable with tags, as I'd like to add my own blocks to the corners and possibly remove those as possibilities.

**Comment by Insane96** [comment]
Added in 3.3.1

**Comment by CraftyZombie** [comment]
Thank you!
