### ISSUE TITLE
Compatibility with Harvest With Ease

### ISSUE THREAD

**Issue by Lonemind** [Insane-96/IguanaTweaksReborn#273]
Minecraft 1.20.1
ITR 3.3.0

It'd be great if you could add compatibility with [Harvest With Ease](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease) to work with the carrot seeds/rooted potatoes.

Harvest with Ease introduces right-click harvesting with crops. The issue between it and ITR is that the carrot seeds/rooted potato are not recognized as seeds or are not prioritized when re-planting a crop. HWE plants the carrot/potato vegetable instead of the seed/root.

I've made an [issue on HWE's github](https://github.com/Crystal-Nest/harvest-with-ease/issues/40) and they suggested you might be able to use their API to solve this issue.

I have not tested other right-click harvesting mods but I suspect they will run into this same issue.

**Comment by Lonemind** [comment]
I have tested this with the new Farmers Delight mod integration and can confirm that the same happens with onions/rooted onions.

**Comment by Insane96** [comment]
Cloing issues to clean up. No plan to add compat with 1.20
