### ISSUE TITLE
Error on Startup with Spice of Life: Valheim Edition

### ISSUE THREAD

**Issue by Talan67** [Insane-96/IguanaTweaksReborn#274]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.4.2
* InsaneLib: 1.13.0

**What Happens**:  
Error on Startup when IguanaTweaks Reborn is loaded with Spice of Life: Valheim Edition, I'm not sure if this is solely an IgaunaTweaks issue.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/Talan67/0bc7660297e565edb3a89b3024c7baf2
https://gist.github.com/Talan67/6e99ffe03d5d49b4e523944ca1cf9256

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
Send the debug.log

**Comment by Insane96** [comment]
Nvm, seems like SOL Valheim is calling getUseAnimation during game load, and there the Features haven't been initialized yet

**Comment by Insane96** [comment]
Could you try again with the latest version?

**Comment by Insane96** [comment]
No follow up, deeming as fixed
