### ISSUE TITLE
3.5.0 Crashes On World-Load (With Only Dependencies)

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#275]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.5.0
* InsaneLib: 1.13.1

**What Happens**:  
Trying to load into a world causes the game to crash. Appears to be complaining about a missing class in EvalEx during the mod's food calculations?

//Please send logs even if you don't have any crash  
(Crash Report, Latest.log, and Debug.log) https://gist.github.com/CraftyZombie/d4b760add7b843280464aadf456e0d0e

//If different from default
**Config**:  
N/A

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes
(IguanaTweaksReborn, InsaneLib, MaxHealthFix)

**Comment by CraftyZombie** [comment]
Just saying, I find it hilarious that thirteen people downloaded this and no one said anything...
<img width="843" alt="Screen Shot 2024-03-07 at 8 31 21 PM" src="https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/374c7725-4f04-4695-9cdb-6666e8d69850">

**Comment by Insane96** [comment]
(Hopefully) fixed in 3.5.1
