### ISSUE TITLE
Chicken Feed

### ISSUE THREAD

**Issue by Lonemind** [Insane-96/IguanaTweaksReborn#276]
Since chicken feed is hardcoded and ITR seems to reduce all possibilities down to only melon seeds and pumpkin seeds, it would be nice to be able to add other modded ways of feeding chickens.
Perhaps add a craftable "chicken feed" item that packdevs can then craft their seeds/modded foods into.

**Comment by Insane96** [comment]
I've added a `iguanatweaksreborn:chicken_food_items` item tag
To be removed in 1.21 since they added their tag
