### ISSUE TITLE
No config option to disable No Hunger under Hunger & Health

### ISSUE THREAD

**Issue by NeuTraLZero** [Insane-96/IguanaTweaksReborn#277]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.17
* IguanaTweaks Reborn: 3.5.0
* InsaneLib: 1.13.2

**What Happens**:  
There is no option to disable No Hunger is the latest version. Trying to add the option and disabling it manually does not work

**Config**:  
https://pastebin.com/4rZKfThy

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
Intended, since 3.5.0 NoHunger can be disabled via gamerule, it's written on the NoHunger config section

**Comment by NeuTraLZero** [comment]
Oh, I missed that completely. Sorry about that
