### ISSUE TITLE
Conflict with iconexporter

### ISSUE THREAD

**Issue by TheFlames096** [Insane-96/IguanaTweaksReborn#278]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.0
* IguanaTweaks Reborn: 3.3.1
* InsaneLib: 1.12.1

**What Happens**:  
The mod conflict with iconexporter which made /iconexport command cannot be use.

**Logs / Crash reports**:  no crash

**Config**:  default

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + Iconexporter 1.2.5)?**:  
Yes

**Comment by Insane96** [comment]
What does it even mean "cannot be use"
Also no logs ...

**Comment by TheFlames096** [comment]
the command/iconexport disappeared at all without any crash/related log output, and it recovered after remove this mod.
Actually this is the strangest bug I've ever seen

**Comment by Insane96** [comment]
Again, I need logs

**Comment by Insane96** [comment]
No follow up, closing
