### ISSUE TITLE
Launching the game told me that the mod had a problem with a block

### ISSUE THREAD

**Issue by fzrdwa123456** [Insane-96/IguanaTweaksReborn#281]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:IguanaTweaks Reborn 1.5.2
* Minecraft:  1.12.2
* Forge: 14.23.5.2860
* IguanaTweaks Reborn: 1.5.2

**What Happens**:  
Explain what's the problem

The game told me that the mod was having problems with a certain block

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
[crash-2024-04-19_04.28.06-client.txt](https://github.com/Insane96/IguanaTweaksReborn/files/15030429/crash-2024-04-19_04.28.06-client.txt)

E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  No change
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  This mod was not uploaded to the mod website
Yes/No

**Comment by Insane96** [comment]
1.12 is no longer supported. Disable the movement restriction module

**Comment by fzrdwa123456** [comment]
> 1.12 is no longer supported. Disable the movement restriction module

Although you no longer support version 1.12.2, thank you for providing the solution. My game is now running normally
