### ISSUE TITLE
The regenerating absorption bar can be longer than 10 icons in length

### ISSUE THREAD

**Issue by jaimarl** [Insane-96/IguanaTweaksReborn#282]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.8.2
* InsaneLib: 1.13.2

**What Happens**:  
When the value of regenerating absorption is greater than 40, the length of the second and subsequent bars becomes 19 icons. Can you also make the number of bars not increase and the whole value is displayed in one bar, for example as in Overflowing Bars?
![2024-04-21_14 15 49](https://github.com/Insane96/IguanaTweaksReborn/assets/139585920/bef610c2-d93e-460e-b447-74662272dbf7)

**Logs / Crash reports**:  https://gist.github.com/Jaimarl/9bedb060f631f468e176b050df707f05

**Config**:  https://gist.github.com/Jaimarl/abb3ed47044338bb9d3d5880487b761f

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
Fixed for next update
