### ISSUE TITLE
Disabling NoHunger in gamerules does not work with ToughAsNails mod

### ISSUE THREAD

**Issue by pxpillon** [Insane-96/IguanaTweaksReborn#283]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.30
* IguanaTweaks Reborn: 3.8.3
* InsaneLib: 1.13.2

**What Happens**:  
As title says. when disabling noHunger in gameRules with ToughAsNails installed, the hunger bar does not show. Works with in-game cheats, but not when creating world/editing the level.dat file directly.

**Logs / Crash reports**:  https://pastebin.com/7xg69nmV

**Config**: https://pastebin.com/cAJJTmp0

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
> Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?:
> Yes

But you didn't send the log with only ITR and TaN

**Comment by pxpillon** [comment]
I apologize. Upon creating a modpack with just ITR and TaN however, the game crashes. Making sure, I disabled TaN and tried to boot up the game, it crashes again. installing ITE seems to fix the issue. 

Heres an example without TaN:
https://gist.github.com/pxpillon/16b893eb0ee6d69beeed530504c32300

heres ITR + ITE + TaN:
https://gist.github.com/pxpillon/dcaeb23af9ecd507643fea3871375580

**Comment by Insane96** [comment]
Did you install InsaneLib and all the other dependencies?|

**Comment by pxpillon** [comment]
they seem to install automatically via curseforge launcher, so yes

Edit: is it supposed to only download Healthfix/Insanelib when installing ITR?

**Comment by Insane96** [comment]
You may have found a huge problem ... good job lol

**Comment by pxpillon** [comment]
ok so i found out just having Serene Seasons, Pehkui, and Mobs Properties randomness with ITR (and healthfix/Insanelib) lets me boot up the game. Would you like me to resend a log of the ToughAsNails issue with just those mods?

**Comment by Insane96** [comment]
Sure, I realized that if you don't have any mod that has mixinextras it crashes the game

**Comment by pxpillon** [comment]
ohh alright. Awesome that you found the issue then :) 

Here's the new log: https://gist.github.com/pxpillon/aa34a527709d6deae857ee2dcfa0d477 
(with just pehkui)

**Comment by Insane96** [comment]
Tough as nails seems to have nothing to do with this. Gonna release a possible fix soon

**Comment by pxpillon** [comment]
ahh. I kinda figured once I eventually noticed the food bar randomly disappearing after I woke up from sleep as well. iirc i think i'd also catch it disappearing when i rejoin a world occasionally. not sure if it pertains to the same issue, but thank you for checking it out.

**Comment by Insane96** [comment]
Closing this and following up in #289
