### ISSUE TITLE
hot reloading common.toml cause noHunger desync

### ISSUE THREAD

**Issue by LTCatt** [Insane-96/IguanaTweaksReborn#289]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.23
* IguanaTweaks Reborn: 3.8.4
* InsaneLib: 1.13.2

I found the no hunger fix in the 3.8.4 changelog, but the hunger bar still doesn't show up when I re-enter the world with 3.8.4
![image](https://github.com/Insane96/IguanaTweaksReborn/assets/40348278/a515fc16-4d66-4615-ae25-221860f577c6)

**Comment by LTCatt** [comment]
Oh, and I think this is another bug related to config file overloading.
First change noHunger to false, at that point change common.toml and switch back to Minecraft and you'll see the hunger bar disappear.

**Comment by Insane96** [comment]
This seems to be a bug related to InsaneLib

**Comment by Insane96** [comment]
Please test with latest InsaneLib

**Comment by LTCatt** [comment]
fixed, thanks!
