### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Xaikii** [Insane-96/IguanaTweaksReborn#29]
1. The Title says it all actually, I would like to increase the hardness overall, and it would be a lot of work to add every block with each meta to the list, and since * is not a viable option for the metas. A simple option to add the hardness to all blocks would be nice.

2. I think this should add some kind of realism to MC and I think you'll agree it is silly to be able to punch a tree... and actually get a drop... an option to disable the use of the hand or add the option that everything has to be mined with the proper tool would be nice, since Adventure Mode does also block Block Placing.

3. Slowness after falling too far down, 3 block = 2 seconds Slowness 1, 5 Blocks = 3 Seconds Slowness 2, etc.

**Comment by Insane-96** [comment]
> The Title says it all actually, I would like to increase the hardness overall, and it would be a lot of work to add every block with each meta to the list, and since * is not a viable option for the metas. A simple option to add the hardness to all blocks would be nice.

Really?
```
 # Multiplier applied to the hardness of blocks (set to 1 to disable). This is applied before the block_hardness (default: 2.0)
    D:multiplier=2.0
```

> I think this should add some kind of realism to MC and I think you'll agree it is silly to be able to punch a tree... and actually get a drop... an option to disable the use of the hand or add the option that everything has to be mined with the proper tool would be nice, since Adventure Mode does also block Block Placing.

How would someone then get wood?

> Slowness after falling too far down, 3 block = 2 seconds Slowness 1, 5 Blocks = 3 Seconds Slowness 2, etc.

I'll think about this

**Comment by Xaikii** [comment]
1. I am using that, but I do not see any difference, same speed every time. 
2. Well like I said an option. Especially in 1.12 there are enough ways to work around not being able to use Fist, e.g. PrimalCore.

**Comment by Insane-96** [comment]
> I am using that, but I do not see any difference, same speed every time.

Just tested it and it works

> Especially in 1.12 there are enough ways to work around not being able to use Fist

So there's no need

> and since * is not a viable option for the metas
It is, just leave meta empty and you'll target every block. E.g. `minecraft:stone` will target stone, diorite, etc.

**Comment by Insane-96** [comment]
> Slowness after falling too far down, 3 block = 2 seconds Slowness 1, 5 Blocks = 3 Seconds Slowness 2, etc.
This is already almost like this. More damage = More stun duration
