### ISSUE TITLE
Game crashes on World Create. 

### ISSUE THREAD

**Issue by thedeviantknight** [Insane-96/IguanaTweaksReborn#290]
**Versions**:
* Minecraft: 1.20.1
* Forge: 47.2.21
* IguanaTweaks Reborn: 3.9.5 - 3.9.6
* InsaneLib: 1.13.4

**What Happens**:  
When starting a new world in single player or starting a server with the above versions of ITR the game/server crashes. 
  
**Logs / Crash reports**:  
https://pastebin.com/CwSSU92j

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
The game crashes because Supplementaries is missing. Releasing a fix soon

**Comment by Insane96** [comment]
Fixed
