### ISSUE TITLE
Piercing damage doesn't ignore Regenerating Absorption

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane-96/IguanaTweaksReborn#292]
// Here your suggestion
Let's say a zombie has, 6 absorption, and your pickaxe is 5.5 damage+ 1 piercing damage. 
The result is that the zombie won't get hurt at all on your first hit, because the direct damage of the pickaxe is 0.5 lower than the zombie's current absorption. In this case the 1 piercing damage entirly goes invalid
But piercing damage literally shall be ignoring the absorption to apply. So the zombie should get 1 point health hurt by the piercing damage, still his current absorption is reduced from 6 to 0.5.

**Comment by Insane96** [comment]
This is a bug then, it should be already the case. It should ignore armor and absorption
