### ISSUE TITLE
another armor indicator appeared on 1.20.1 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Insane-96/IguanaTweaksReborn#293]
![20240529_051340](https://github.com/Insane96/IguanaTweaksReborn/assets/169136387/197650ac-3445-4dce-b4b7-736e1b8868a4)

**Comment by Insane96** [comment]
Does it happen with ITR only?

**Comment by FilipKompaniets3** [comment]
> Чи відбувається це лише з ITR?

Yes! This is bug

**Comment by Insane96** [comment]
Then send the config. You just deleted all the template you should have followed

**Comment by FilipKompaniets3** [comment]
[1qRpznt_9HnJcG-3JC6PtSA.json](https://github.com/Insane96/IguanaTweaksReborn/files/15484727/1qRpznt_9HnJcG-3JC6PtSA.json)

**Comment by FilipKompaniets3** [comment]
[ITRC.zip](https://github.com/Insane96/IguanaTweaksReborn/files/15485007/ITRC.zip)

**Comment by Insane96** [comment]
Also logs

**Comment by FilipKompaniets3** [comment]
I do not know what is this

**Comment by FilipKompaniets3** [comment]
When I tested an older version of the mod on 1.20.1, I didn’t have that bug

**Comment by FilipKompaniets3** [comment]
> Також колоди

Is this what you meant? 

[Logs.zip](https://github.com/Insane96/IguanaTweaksReborn/files/15487633/Logs.zip)

**Comment by FilipKompaniets3** [comment]
Thank you :)
