### ISSUE TITLE
Portal Corners are Incompatible with Spelunkery's Dimension Tears Activation.

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#295]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.1
* IguanaTweaks Reborn: 3.12.0
* InsaneLib: 1.13.5

**What Happens**:  
IguanaTweaks Reborn makes it so that there can be a specific requirement for the corners of Nether portals before they are lit. Spelunkery, the conflicting mod, adds a new item (The Bottle o' Dimensional Tears), which allows the lighting of Nether portals without flint and steel. However, lighting the portal in this manner bypasses the requirement to fill the portal corners.

![2024-06-09_17 35 21](https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/dc2944f1-f01f-4228-b07a-b63e206312b2)

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
[E.g. https://pastebin.com/1AbCDEFG](https://gist.github.com/CraftyZombie/f1aa0903fba073c8709a0afe554781f7)
(latest.log and debug.log)

//If different from default
**Config**:  
Configs from all mods remain unchanged.

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes.

IguanaTweaks Reborn - 3.12.0
InsaneLib - 1.13.5
MaxHealthFix - 12.0.3
Spelunkery - 0.3.5
Moonlight Library - 2.11.33

**Comment by Insane96** [comment]
I'm using the Forge event to check for corners. Report to them as seems like they're not using the event
