### ISSUE TITLE
Creating a new world will cause `no_hunger` to be set to true

### ISSUE THREAD

**Issue by LTCatt** [Insane-96/IguanaTweaksReborn#296]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.23
* IguanaTweaks Reborn: 3.12.0
* InsaneLib: 1.13.5

**What Happens**:  
Creating a new world will cause `no_hunger` config to be set to true
![image](https://github.com/Insane96/IguanaTweaksReborn/assets/40348278/3b2fd3c6-e2c0-42ce-a672-f3ad18153e7d)
https://discord.com/channels/435418419496615946/435419210965843979/1249107890568953856

**Comment by Insane96** [comment]
I plan on removing the gamerule next release
