### ISSUE TITLE
Make absorption hit sound a datapack assets driven one instead of a fixed distorted item_break sound

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane-96/IguanaTweaksReborn#297]
// Here your suggestion
As mentioned. Here're the two sounds I'd like to apply to replace the absorption hit sound.
[Absorption hit.zip](https://github.com/user-attachments/files/15897758/Absorption.hit.zip)

**Comment by Insane96** [comment]
Thanks, I had already forgot about this
