### ISSUE TITLE
The display of regenerating absorption is broken

### ISSUE THREAD

**Issue by jaimarl** [Insane-96/IguanaTweaksReborn#298]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: 3.12.0
* InsaneLib: 1.13.5

**What Happens**:  
If the regenerating absorption value is greater than or equal to 20, the icons are shifted to the right. Also, the regeneration bar is not under the health bar, but under the top row of regenerating absorption.
![image](https://github.com/Insane96/IguanaTweaksReborn/assets/139585920/c86cfd32-6366-4f47-89e9-f3712e1cd633)

**debug.log / Crash reports**:  
https://gist.github.com/Jaimarl/2b5aa4c27f968a19330775b1cb836c72

**Config**:  
https://gist.github.com/Jaimarl/4011492c089bd320ad09d9f43bed9748

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
Any screenshot?
