### ISSUE TITLE
1.20.1-wiki-json

### ISSUE THREAD

**Issue by YuKiYimin** [Insane-96/IguanaTweaksReborn#299]
I wrote a JSON according to the wiki, but no matter how I modify it, I can't succeed.Can you provide more specific information from the wiki, or give me an example?

`{
    "PlantGrowthModifier": [
      {
        "block": "minecraft:beetroots",
        "growth_multiplier": 1.1,
        "no_sunlight_growth_multiplier": 0.5,
        "min_sunlight_required": 1,
        "night_time_growth_multiplier": 0.75,
        "correct_biomes": [
        ],
        "wrong_biome_multiplier": 0.3,
        "inverse_correct_biomes": true,
        "season_multipliers": [
          {
            "season": "SPRING",
            "multiplier": 1.2
          },
          {
            "season": "SUMMER",
            "multiplier": 1.0
          },
          {
            "season": "AUTUMN",
            "multiplier": 0.8
          },
          {
            "season": "WINTER",
            "multiplier": 0.6
          }
        ]
      }
    ]
  }`

**Comment by Insane96** [comment]
Don't use GitHub for problems you're having. Use discord
