### ISSUE TITLE
After Portal Activation, Corners Don't Matter Anymore

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#302]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.4
* IguanaTweaks Reborn: 3.13.2
* InsaneLib: 1.13.5

**What Happens**:  
Explain what's the problem
When ITR's portal corners requirement is on, you need the corners to be filled (by default with crying obsidian) for the portal to _activate_, but then you can remove those blocks.

![2024-07-03_16 50 37](https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/dc09abed-786c-4b6a-b361-c9b0d24155fe)
![2024-07-03_16 50 48](https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/0aae7a1f-955a-4634-993e-9efa54fbb107)
![2024-07-03_16 51 03](https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/f6e8ab19-a897-470a-a7aa-f4d0fb1d4763)

**debug.log / Crash reports**:  
https://pastebin.com/1AbCDEFG](https://gist.github.com/CraftyZombie/1a6b8b7c49be6906c2e380406c396aea

**Config**:  
Unaltered.

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes, this is an IguanaTweaks-specific issue. Not a mod conflict.

**Comment by Insane96** [comment]
That's intended

**Comment by Insane96** [comment]
Let me be more specific. That's intented as if you want to lit back up the portal you still need the corners. There's no way to tell if the portal is "valid" when breaking the block (unless many calculations are done which I don't see the point)

**Comment by CraftyZombie** [comment]
Got it. Thanks.
