### ISSUE TITLE
Crash with Terralith (And presumably other Worldgen Mods)

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#303]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.4
* IguanaTweaks Reborn: 3.13.2
* InsaneLib: 1.13.5

**What Happens**:  
Explain what's the problem
The game crashes during worldgen.
Based on the crash, it seems that you've programmed a feature to generate in different biome tags. A single Terralith biome has both, which confuses the worldgen. The solution is to make a biome tag for your feature and add other biome tags to it.
A similar issue: https://github.com/Lothrazar/Cyclic/issues/2388

**debug.log / Crash reports**:  
latest/debug/crash: https://gist.github.com/CraftyZombie/1a0631399d57cc6cb4b5f0e3cc11943d

//If different from default
**Config**:  
Unaltered.

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes; Terralith 2.5.1

**Comment by Insane96** [comment]
Duplicate, check pinned issue

**Comment by CraftyZombie** [comment]
Whoops, apologies
