### ISSUE TITLE
Config Option for Merging Enchantments in Anvil

### ISSUE THREAD

**Issue by DeliciousTea** [Insane-96/IguanaTweaksReborn#304]
I've looked through the config & data and messed with a bunch of settings but I don't see this option. I'd like for merging items, specifically for putting enchantments onto items to cost XP while retaining xp free renaming and repairs.

**Comment by Insane96** [comment]
You want to add enchantments to items with books?

**Comment by Insane96** [comment]
Closing for no follow up
