### ISSUE TITLE
[Minor Bug] Enchantment Descriptions' info not showing

### ISSUE THREAD

**Issue by ShinryuAspect** [Insane-96/IguanaTweaksReborn#305]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.5
* IguanaTweaks Reborn: 3.13.2
* InsaneLib: 1.13.5

**What Happens**:  
It's just a minor bug with Enchantment Descriptions as it fails to read from the lang file due to wrong format. Every enchantment within the lang .json ends with ".info" instead of ".desc", which is the format ED uses.
EDIT: Forgot to say it happens both with Reborn and Expanded.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**debug.log / Crash reports**:  

//If different from default
**Config**:  

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes.

**Comment by Insane96** [comment]
The mod has it's own enchantment descriptions
