### ISSUE TITLE
Crash when trying to create a new wordl (Generation: Teralith)

### ISSUE THREAD

**Issue by IonM-2000** [Insane-96/IguanaTweaksReborn#306]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: IguanaTweaksReborn-3.13.2-mc1.20.1
* InsaneLib: InsaneLib-1.13.5-mc1.20.1
* MaxHealthFix-Forge-1.20.1-12.0.3
* Terralith_1.20.x_v2.5.4

**What Happens**:  
When I try to create a new world it crashes, when I tried without iguanatweaks it worked perfectly fine. I don't really thing there is a problem on Teralith side but gonna write to them as well. The crash report:
https://pastebin.com/09JS83Yf

Log:
https://pastebin.com/M4EzEusS

Config is default

I tried only with this four mods to isolate the issue

**Comment by Insane96** [comment]
Pinned issues
