### ISSUE TITLE
[1.20.1] Better hardcore death not working

### ISSUE THREAD

**Issue by Mic1e** [Insane-96/IguanaTweaksReborn#308]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.5
* IguanaTweaks Reborn: 3.13.4
* InsaneLib: 1.13.5

**What Happens**:  
With the Better hardcore death option enabled, the player does not respawn in a hardcore world, the lightning strikes but the player remains in spectator mode instead of respawning.

**debug.log / Crash reports**:  
https://mclo.gs/2KDVWDM

**Config**:  
Default

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
- IguanaTweaks Reborn
- InsaneLib
- MaxHealthFix

**Comment by Insane96** [comment]
That's the point of the feature ... you can't respawn in hardcore

**Comment by Mic1e** [comment]
Ok, in that case I think this description on the website stating:
> Dying in hardcore now respawns you in the spot you died

is a bit confusing because it doesn't respawn you, it just sets your position to where you died.

**Comment by Insane96** [comment]
You click "respawn", so you respawn, but in spectator
