### ISSUE TITLE
[1.20.1] Black screen with the tired effect.

### ISSUE THREAD

**Issue by Mic1e** [Insane-96/IguanaTweaksReborn#309]
**Versions**:
* Minecraft: 1.20.1
* Forge: 47.3.5
* IguanaTweaks Reborn: 3.13.4
* InsaneLib: 1.13.5

**What Happens**:  
When the player gets the Tired effect the screen goes black leaving only the HUD visible and a little spot near the center of the screen.
![image](https://github.com/user-attachments/assets/7c3e2eb4-ac4a-43af-a33f-9745bfe6c06e)

**debug.log / Crash reports**:  
https://mclo.gs/GxENDB7

**Config**:  
[common.toml](https://pastebin.com/4twDAVZ7)
[client.toml](https://pastebin.com/FSMMaNGY)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Not sure yet, I'll post updates on a minimal mod list when I have more time.

**Comment by Insane96** [comment]
No updates. Closing
