### ISSUE TITLE
configurable weights of mod items like old versions

### ISSUE THREAD

**Issue by mzldh** [Insane-96/IguanaTweaksReborn#31]
HI, rebuild of this mod, really appreciate seeing a mod that adds more realistic survival factors to the game community. Thank you for creating this!

however, it does seem odd that the weights.jason file is nowhere to be found in the config file. or the entire . minecraft folder. 

I wonder if the weights of mod items are still configurable or not, please do realize this is honestly a rather great deal of a survival mod

I hope to hear from you soon about this matter, good luck!

**Comment by Insane-96** [comment]
I've never seen any weights.json file in the source code. That might be because I've ported the original 1.6 version and never looked at the 1.7 version from parker.

**Comment by mzldh** [comment]
Yes, though it would be nice to have the stacks and weights of other mods configurable in config or some sort of script. A lot of mod pack people wants to encourage players to build railroads and use transport vehicles.

 Back in 1.7.10 I’ve experienced a war/tech server that uses iguana tweaks, bans all teleportation, and encourage players to build railroads and high ways to transport resources and ammunition. It was pretty cool

**Comment by Insane-96** [comment]
Stacks and single block hardness already are.
