### ISSUE TITLE
Crash with Tiredness Effect

### ISSUE THREAD

**Issue by katubug** [Insane-96/IguanaTweaksReborn#311]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.7
* IguanaTweaks Reborn: 3.14.5
* InsaneLib: 1.14.0

**What Happens**:  
I'm not actually sure, I was tabbed out when my game crashed.

**debug.log / Crash reports**:  
https://gist.github.com/katubug/a667bf131e9da82aff9299ff385eef01

**Config**:  
also https://gist.github.com/katubug/a667bf131e9da82aff9299ff385eef01

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
I did not try, but I will if I need to.

**Comment by Insane96** [comment]
Fixed for next update
