### ISSUE TITLE
Ticking entity Crash if Serene Season is not installed

### ISSUE THREAD

**Issue by RafaelGuiFernandes** [Insane-96/IguanaTweaksReborn#313]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: 3.15.3
* InsaneLib: 1.15.0

**What Happens**:  
Game Crashes on world loading if Serene Seasons is not installed , IguanaTweaks Expanded is not installed

//Please send logs even if you don't have any crash  
[crash-2024-09-22_22.15.54-server.txt](https://github.com/user-attachments/files/17091911/crash-2024-09-22_22.15.54-server.txt)
[latest.log](https://github.com/user-attachments/files/17091912/latest.log)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
Fixed for next update
