### ISSUE TITLE
Explosion sound file doesn't play at a certain distance

### ISSUE THREAD

**Issue by NotoriousCoke** [Insane-96/IguanaTweaksReborn#314]
Forge 1.20.1

The explosion sound doesn't properly play at a distance. This applies to all explosives including TNT and modded explosives.

https://github.com/user-attachments/assets/ebe6ab95-42c4-4818-89af-164e1dec542d

**Comment by NotoriousCoke** [comment]
![image](https://github.com/user-attachments/assets/2bf82d61-ece6-4c1f-87d1-4e9c321f05cd)

modlist

**Comment by Insane96** [comment]
There's a reason why there's a template you must fill. Reopen this and don't ignore the template
