### ISSUE TITLE
1.20.1 Forge Server fails to start

### ISSUE THREAD

**Issue by paulogoodman** [Insane-96/IguanaTweaksReborn#315]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**: 
* Minecraft:  1.20.1
* Forge: 47.3.0 and 47.3.10
* IguanaTweaks Reborn: 3.16.1
* InsaneLib: 1.15.0

**What Happens**:  

Forge server fails to start. 

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**debug.log / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

Crash Log: https://pastebin.com/aLzAWyFB
Server Log: https://pastebin.com/W5qWaG4L

//If different from default
**Config**:  

Completely default installation.

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Reproducible using the bare minimum. InsaneLib, Iguanatweaks reborn and maxhealthfix.

**Comment by Insane96** [comment]
Fixed in 3.16.2
