### ISSUE TITLE
Failure to load with Serene Seasons 9.1.0.0

### ISSUE THREAD

**Issue by katubug** [Insane-96/IguanaTweaksReborn#316]
**Versions**:
* Minecraft:  1.20.1
* Forge:  47.3.7
* IguanaTweaks Reborn: 3.18.1
* InsaneLib: 1.15.0

**What Happens**:  
The game refuses to load and gives an error.

**debug.log / Crash reports**:  
https://gist.github.com/katubug/6db0e67c612ebc449f44d52b5a116071

**Config**:  
[iguanatweaksrebornBACKUP.zip](https://github.com/user-attachments/files/17296431/iguanatweaksrebornBACKUP.zip)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
I haven't tried yet, still testing things.

**Comment by katubug** [comment]
- Tested with default configs, no dice.

- Tested with fully deleted and reinstalled IguanaTweaks/InsaneLib just in case it was file corruption; still erroring: https://i.imgur.com/EpVYq9v.png

- For sanity, tested without IguanaTweaks/InsaneLib and it does load.

- Now testing last known working version, 3.15.0 - actually it still crashes but it's a little more helpful: https://gist.github.com/katubug/a328e7ca6c677a724c26326e213edd28

- Now gonna try reverting Serene Seasons update.

**Comment by katubug** [comment]
Okay, so I reverted all changes to when I knew it was working, then updated IguanaTweaks to latest, and it loads fine. So the issue must be with another mod, I'll report back when I know what it is.

**Comment by katubug** [comment]
The issue seems to be with the latest Serene Seasons update. It works fine with Serene Seasons 9.0.0.46, but not 9.1.0.0

**Comment by Insane96** [comment]
Will not fix. They decided to mess stuff up by porting the changes from Fabric 1.20.4 breaking every compatiblity. Next ITR version will tell you that the latest version is not compatible.

**Comment by katubug** [comment]
Just as a note, this inadvertently makes the most recent versions of Legendary Survival Overhaul incompatible with ITR, as they are now *only* compatible with Serene Seasons 9.1.0.0 :(
