### ISSUE TITLE
Possible Thunderstorm Crash

### ISSUE THREAD

**Issue by Lonemind** [Insane-96/IguanaTweaksReborn#317]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.21.0
* InsaneLib: 1.15.0

**What Happens**:  
Sudden crash out of nowhere. Judging from the crash log I suspect an ITR thunderstorm started and tried to "divide by zero" somewhere, causing the crash. Disabling Weather in the config stopped the crashes.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin** 

https://pastebin.com/UbdEjTpZ

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
I admit, I did not try before I had to leave for work. I will attempt it this evening.

**Comment by Insane96** [comment]
Did you change min intensity to 0?

**Comment by Insane96** [comment]
I have no idea why this is happening, it should be impossible for intensity to be 0

**Comment by Lonemind** [comment]
Well, I am unable to reproduce this on a minimal set of mods so I can only assume it is a bad interaction with another mod I am using. Thank you for your input, Insane.
