### ISSUE TITLE
Crash with JCraft

### ISSUE THREAD

**Issue by A4AAAAAA** [Insane-96/IguanaTweaksReborn#318]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.5
* IguanaTweaks Reborn: 3.21.0
* InsaneLib: 1.15.0
*JCraft: 0.15.3

**What Happens**:  
Starting the game doesn't work. Game pops up and closes again. No crash report is generated.

//Please send logs even if you don't have any crash  
https://pastebin.com/xKMGeBtP

//If different from default
**Config**:  
https://pastebin.com/6VwrEJ8B

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes, you'll need Jcraft and Iguana Tweaks. For Satin there is a dropbox link in the mod description for Jcraft, it does say 1.18.5 but that's the only version and it is working with that.

**Comment by Insane96** [comment]
Update InsaneLib. It's a really older version

**Comment by A4AAAAAA** [comment]
sorry wrote the wrong version for some reason

**Comment by Insane96** [comment]
I need the debug.log, the log shows nothing. Also the log you sent doesn't have only the coulprit mods

**Comment by A4AAAAAA** [comment]
sorry it doesn't give me a debug log, I have the option activated in the curseforge launcher and looked in the logs folder but there isn't one being generated. Also I redid the modpack without the other mods: https://pastebin.com/jmM7ZmfY

**Comment by Insane96** [comment]
> sorry it doesn't give me a debug log, I have the option activated in the curseforge launcher and looked in the logs folder but there isn't one being generated. Also I redid the modpack without the other mods: https://pastebin.com/jmM7ZmfY

This works

**Comment by Insane96** [comment]
Basically ITR is applying a mixin (change into Minecraft's code) in the same place as JCraft.
Possibly fixed next update

**Comment by Insane96** [comment]
Please note that ITR will now take priority as their mod is not open source so I can't do much beside that
