### ISSUE TITLE
Big tick time for onCollideWithWall() even disabled

### ISSUE THREAD

**Issue by DaftHunk** [Insane-96/IguanaTweaksReborn#319]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**: 
* Minecraft:  1.20.1
* Forge: 47.2.36
* IguanaTweaks Reborn: 3.21.1
* InsaneLib: 1.15.0

**What Happens**:  
Big tick time for onCollideWithWall() even disabled is disabled
https://spark.lucko.me/j37MsTPfeb

**Config**:  
https://pastebin.com/TAR5hb7Q

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
<Your answer here>

**Comment by DaftHunk** [comment]
![Capture d’écran 2024-10-27 191831](https://github.com/user-attachments/assets/e0bd1ab4-0491-4c5b-aeee-22ec6934f5be)

**Comment by Insane96** [comment]
This is not an issue, it's spark behaving incorrectly. Spark is saying that the vanilla method is taking time to process, I just call that. 
From what I can see, Valkirien skies is slowing down the processing 
![image](https://github.com/user-attachments/assets/44532e01-0101-49ff-80eb-31e7160abd5a)

**Comment by Insane96** [comment]
But as I check out the code, yes, you can't disable it (will still show up in spark). Will fix for next update

**Comment by Insane96** [comment]
Fixed the fact that you can't disable the feature for next update

**Comment by DaftHunk** [comment]
Awesome, thank you !
