### ISSUE TITLE
`Block Break Exhaustion Multiplier` and `Exhaustion per tick when breaking a block` don't seem to have any effect

### ISSUE THREAD

**Issue by LTCatt** [Insane-96/IguanaTweaksReborn#320]
**Versions**:
* Minecraft:  1.20.1
* IguanaTweaks Reborn: 3.21.1
* InsaneLib: 1.15.0

**What Happens**:  
`Block Break Exhaustion Multiplier` and `Exhaustion per tick when breaking a block` don't seem to have any effect.
![image](https://github.com/user-attachments/assets/c5e350d6-7f43-4637-811d-2b2f04427142)

**Config**:  
[common.zip](https://github.com/user-attachments/files/17569016/common.zip)

**Comment by Insane96** [comment]
Did you check in F3 if exhaustion increases? (Remember that you have to enable F3 back with the gamerule)

**Comment by LTCatt** [comment]
checked. it doesn't change.

**Comment by Insane96** [comment]
Thanks. I'm out of town for a few days so I'll check when I'm back

**Comment by Insane96** [comment]
You have exhaustion increase disabled

**Comment by LTCatt** [comment]
oh I'm so sorry. I forgot that I made another tweak that also did Passive Exhaustion, so I assumed I'd turned that feature on...
