### ISSUE TITLE
`Peaceful Hunger & Health = false` prevents hunger reduction

### ISSUE THREAD

**Issue by LTCatt** [Insane-96/IguanaTweaksReborn#321]
**Versions**:
* Minecraft:  1.20.1
* IguanaTweaks Reborn: 3.21.1
* InsaneLib: 1.15.0

**What Happens**:  
`Peaceful Hunger & Health = false` prevents hunger reduction, even on non-peaceful difficulties
![1](https://github.com/user-attachments/assets/d0944293-bf52-4c6f-9abf-32bd482dee3a)

**Config**:  
[common.zip](https://github.com/user-attachments/files/17570173/common.zip)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes
![image](https://github.com/user-attachments/assets/698b8f33-f52c-4cc8-aba1-ee330f36a548)

**Comment by Insane96** [comment]
Thanks, As said, I'm out of town so will chech it in some days

**Comment by Insane96** [comment]
For future me:

`			else if (peacefulHunger && difficulty != Difficulty.PEACEFUL) {`

This is supposed to be an OR and not AND

**Comment by Insane96** [comment]
Fixed for next update
