### ISSUE TITLE
Changing `food_properties.json` for `betterend:cave_pumpkin_pie`, but it also applies to `minecraft:pumpkin_pie`

### ISSUE THREAD

**Issue by LTCatt** [Insane-96/IguanaTweaksReborn#322]
**Versions**:
* Minecraft: 1.20.1
* Using Connector to use better end

**What Happens**:  
![image](https://github.com/user-attachments/assets/36c0fff4-3d33-4825-8157-a09d190a93cd)

It looks like `IdTagMatcher` did something weird.
https://github.com/Insane96/IguanaTweaksReborn/blob/29d1693243c807332d9d7aab9270ce26ba8822c9/src/main/java/insane96mcp/iguanatweaksreborn/module/hungerhealth/fooddrinks/CustomFoodProperties.java#L20

**Config**:  
\config\iguanatweaksreborn\Hunger & Health\Foods & Drinks\food_properties.json
```json
[{"food": "betterend:cave_pumpkin_pie", "nutrition": 20}]
```

**Comment by Insane96** [comment]
I can't really test this. There's no way to run fabric mods in a forge dev environment.
Do the items actually give 20 health or is just visual? Did you try eating them?

**Comment by LTCatt** [comment]
hmm let me see if there's any other way to reproduce

**Comment by LTCatt** [comment]
I investigated a bit more and this should be because Better End is using the same instance of FoodProperties when registering food, causing one to be modified when the other is modified.

[Code](https://github.com/paulevsGitch/BetterEnd/blob/a1ad58cf5462fcb7b3e26eda5300c25e8f5603c5/src/main/java/ru/betterend/registry/EndItems.java#L183)
```java
	public final static Item CAVE_PUMPKIN_PIE = registerEndFood("cave_pumpkin_pie", Foods.PUMPKIN_PIE);
	public static Item registerEndFood(String name, FoodProperties foodComponent) {
		return getItemRegistry().registerFood(BetterEnd.makeID(name), foodComponent);
	}
```

Perhaps this can be circumvented by creating a clone of the FoodProperties and making changes to the cloned instance when it is modified?

**Comment by Insane96** [comment]
So BetterEnd is needed?

**Comment by LTCatt** [comment]
Yes, I can't reproduce this with other mods.

**Comment by Insane96** [comment]
> I investigated a bit more and this should be because Better End is using the same instance of FoodProperties when registering food, causing one to be modified when the other is modified.
> 
> [Code](https://github.com/paulevsGitch/BetterEnd/blob/a1ad58cf5462fcb7b3e26eda5300c25e8f5603c5/src/main/java/ru/betterend/registry/EndItems.java#L183)
> 
> ```java
> 	public final static Item CAVE_PUMPKIN_PIE = registerEndFood("cave_pumpkin_pie", Foods.PUMPKIN_PIE);
> 	public static Item registerEndFood(String name, FoodProperties foodComponent) {
> 		return getItemRegistry().registerFood(BetterEnd.makeID(name), foodComponent);
> 	}
> ```
> 
> Perhaps this can be circumvented by creating a clone of the FoodProperties and making changes to the cloned instance when it is modified?

Then this is exactly the problem. It's up to them to use a new instance of the food component.
