### ISSUE TITLE
New version doesn't fix #323 #319 on my side

### ISSUE THREAD

**Issue by DaftHunk** [Insane-96/IguanaTweaksReborn#324]
Hello ! Sorry to bother again, but I still have those issues with the latest version

**Comment by DaftHunk** [comment]
#323 #319

**Comment by Insane96** [comment]
Which enchantments are you still seeing?

As for the collide you should be able to disable it

**Comment by Insane96** [comment]
Btw you could have re-opened the issues

Il Gio 7 Nov 2024, 18:40 DaftHunk ***@***.***> ha scritto:

**Comment by DaftHunk** [comment]
Maybe I'm doing something wrong, here is my configs :
https://pastebin.com/2FcRDyB5
Here is the spark where you can see insane96mcp.iguanatweaksreborn.module.misc.tweaks.Tweaks.onCollideWithWall() still present :
https://spark.lucko.me/P7GBb1QZco
And for the enchants it's all of them, for exemple this one :
![2024-11-07_21 13 12](https://github.com/user-attachments/assets/b09151cd-84f2-4605-ba92-37643877f813)

**Comment by Insane96** [comment]
So, for the collide with wall that's normal. Even when disable it will still call the vanilla move method. 
As for enchantments I'll take a look. Will reopen the issue and close this one
