### ISSUE TITLE
NostalgicTweaks HUD Conflict With ITR

### ISSUE THREAD

**Issue by Morealess** [Insane-96/IguanaTweaksReborn#325]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: 3.21.0
* InsaneLib: 1.15.0

**What Happens**:  
Preface: the behavior is pretty strange so it's difficult to explain, but I'll try to get everything - NostalgicTweaks updated for beta 9 and this introduced a conflict with IguanaTweaksReborn which if NT "hideHungerBar" config is true (removes the hunger bar, puts air level bar above hearts and armor in place of hunger bar), and without any armor equipped, the air level bar will render with a gap between it and the hearts bar - but if you have armor equipped, then there is no gap and it renders flush overtop the hearts as per usual. There is also another interaction which seems to be related and likely the cause of this in the first place which is ITR > Hunger & health > No Hunger > Render Armor At Hunger; when enabled with NT "hideHungerBar", this fixes the gap between the air and hearts bars without armor equipped, but then the armor bar becomes invisible - presumably because it is literally "rendering the armor at hunger" whereas the hunger bar would be removed by NT. I also tried disabling the Hunger & Health module entirely and the initial problem persists. There seems to be no config to fully stop ITR from messing with the air/armor bars, like it's baked into the client somehow which interferes with the changes NT made in beta 9+. So while I recognize that this is for the most part on behalf of NT to resolve, I feel like this could/hopefully be worthwhile to look into as whatever the cause could also potentially interfere with other mods doing anything to armor/air bars just based on the nature of the overlap - and well, NT apparently seems to be on hiatus. I'd be excited and thrilled honestly for a fix, these 2 mods are perfect together. And happy to help any ways I can! Thanks for your incredible work!

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  

**debug.log / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

//If different from default
**Config**:  
E.g. https://pastebin.com/1AbCDEFG

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes, only NostalgicTweaks, Architectury, IguanaTweaksReborn, InsaneLib, MaxHealthFix are req

![2024-11-09_20 47 39](https://github.com/user-attachments/assets/df8c6892-1519-4e05-8fe7-80c25d4b34e2)
![2024-11-09_20 48 35](https://github.com/user-attachments/assets/d9edbe4c-656a-4efd-a3fc-c9a0b506db75)

**Comment by Insane96** [comment]
I'm using nostalgic tweaks with ITR and don't have this problem.
These are the configs I'm using
https://github.com/Insane96/SurvivalReimagined/tree/beta/config

Note: I've disabled NT changes and used ITR's ones

**Comment by Morealess** [comment]
This is because Eye Candy > "hideHungerBar": false - if you set to true to use NT layout it does as described. The problem is that there doesn't seem to be a way to stop ITR from interfering with this config, and misaligning the air bar without armor equipped. You can disable every config in ITR and it still causes this? That's why I believe it might be worthwhile to investigate, and hopefully can be fixed 

And additionally I'll reiterate, if: ITR > Hunger & health > No Hunger > Render Armor At Hunger is enabled with NT hideHungerBar it fixes the air bar misalignment as previously described without armor equipped, but then makes the armor bar invisible. 

So while yes you can disable NT hideHungerBar and avoid this overlap entirely, if you do prefer NT/original layout and enable hideHungerBar, then there exists these 2 different conflicts that arise solely from hideHungerBar enabled and ITR installed alongside! (off topic - but I'd recommend maybe adding a b1.7.3 "render armor at hunger" like config, which puts air above hearts instead of above armor like it currently does? I feel like would only make sense as this tweak is already replicating the old mechanic, just lacking the equivalent hud). Fingers crossed you consider fixing this, absolutely love your mod(s)

**Comment by Insane96** [comment]
I'm not gonna fix the bug from NT since can be easily avoided by using ITR config.

As for the air meter I never realized that it was over the health back in beta. I'll add a new config option to move it, even tho I don't see the point.

**Comment by Insane96** [comment]
Closing. Will not add the air meter config option. There's really no point
