### ISSUE TITLE
Crash: Exception ticking world - when weather is thunder in modpack

### ISSUE THREAD

**Issue by FeedingTheDragons** [Insane-96/IguanaTweaksReborn#326]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 1.20.1-47.3.7
* IguanaTweaks Reborn: 3.21.2-mc1.20.1
* InsaneLib: 1.15.0

**What Happens**: 
Modpack: Dying of the Light.
The game crashes sometimes when the weather is "thunder". I am able to start up normally again after the crash, but it will crash again soon after. Every other weather is fine. The crash isn't instantly, just seemingly random over the course of a thunder storm. I hope i gave all the proper information.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**debug.log / Crash reports**: 

[latest.log](https://github.com/user-attachments/files/17691528/latest.log)
[crash-2024-11-10_14.02.36-server.txt](https://github.com/user-attachments/files/17691512/crash-2024-11-10_14.02.36-server.txt)

//If different from default
**Config**: 
[iguanatweaksreborn-configs.zip](https://github.com/user-attachments/files/17691519/iguanatweaksreborn-configs.zip)

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
I don't know. I never used this weather mod and i'm not even sure which weather mod it is.

**Comment by Insane96** [comment]
This is an old version of ITE. Update

**Comment by FeedingTheDragons** [comment]
What does ITE mean?

**Comment by Insane96** [comment]
IguanaTweaks Reborn

**Comment by FeedingTheDragons** [comment]
This isn't the newest version?
IguanaTweaks Reborn: 3.21.2-mc1.20.1
I'm sorry if i'm being annoying.

**Comment by Insane96** [comment]
Yep, seems like another crash

**Comment by Insane96** [comment]
For reference, I need to change this https://github.com/Insane96/IguanaTweaksReborn/blob/32aa4a51b09ca27f1c3712fe2778157271c22f6d/src/main/java/insane96mcp/iguanatweaksreborn/module/world/weather/WeatherSavedData.java#L91 to check on load.

**Comment by FeedingTheDragons** [comment]
[crash-2024-11-11_22.14.03-server.txt](https://github.com/user-attachments/files/17708767/crash-2024-11-11_22.14.03-server.txt)

Maybe the latest crash report might help. It may have somthing to do with the chance of getting struck by lightning?

**Comment by Insane96** [comment]
The problem is that when data is first loaded, the intensity is set to 0, so it divides by 0 and crashes

**Comment by FeedingTheDragons** [comment]
Okay, thank you. Dunno if i can do anything, but i'm glad to know what's the main problem and that i can avoid it. I hope it's useful for you, too.

**Comment by Insane96** [comment]
In the meantime you can disable the Weather feature

Il Mar 12 Nov 2024, 10:47 FeedingTheDragons ***@***.***> ha
scritto:
