### ISSUE TITLE
[1.20.1] Incompatibility Issue with SOL Valheim

### ISSUE THREAD

**Issue by A4AAAAAA** [Insane-96/IguanaTweaksReborn#327]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.20.1 
* Forge: 47.3.12
* IguanaTweaks Reborn: 3.21.2
* InsaneLib: 1.15.0

**What Happens**:  
Crash upon starting the game, incompatability issue with SOL Valheim. Seemingly an old issue but on a newer version of Iguana Tweaks

//Please send logs even if you don't have any crash  
Crash Report: https://pastebin.com/QARfXeD4
Logs: https://pastebin.com/h9cmgC6s

Can be reproduced with a minimal set of mods? IguanaTweaks Reborn + InsaneLib + SOL Valheim Updated

**Comment by Insane96** [comment]
SOL config is calling getUseAnimation too soon in the mod lifecycle. I can't do anything

**Comment by A4AAAAAA** [comment]
Alright still thanks for looking into it, didn't know if it was still the old problem or a new one.

**Comment by Insane96** [comment]
Unless more stuff breaks I might be able to fix this
