### ISSUE TITLE
Crash whilst exception ticking world: Error java.lang.ArithmeticException: / by zero. [1.20.1 / 3.21.3]

### ISSUE THREAD

**Issue by Hidden44** [Insane-96/IguanaTweaksReborn#328]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.20.1
* Forge: 47.3.12
* IguanaTweaks Reborn: 3.21.3
* InsaneLib: 1.15.1

**What Happens**:  
Loading the world during a thunderstorm will crash.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**debug.log / Crash reports**:  
https://pastebin.com/5KU6dhZ4

//If different from default
**Config**:  
https://pastebin.com/iSq2SdJV

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Most likely, considering the first line in the crash report says its from the World module: Weather from iguanatweaksreborn mod.

**Comment by Hidden44** [comment]
Thanks, glad to know this is being ignored.

**Comment by Insane96** [comment]
I've fixed this as you saw for the completed commit, the commit message where I fixed this issue and a new released version that literally states "fixed a Thunderstorm intensity crash". You're welcome

**Comment by Hidden44** [comment]
..Apologzies, I don't know how github works. I just assumed the statement "Not following this guidline will result in ignored and closed issue."

**Comment by Insane96** [comment]
You followed it .. so
