### ISSUE TITLE
[1.20.1] Incompatibilty with JJThunder King of the Hills

### ISSUE THREAD

**Issue by A4AAAAAA** [Insane-96/IguanaTweaksReborn#329]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.20.1 
* Forge: 47.3.12
* IguanaTweaks Reborn: 3.21.4
* InsaneLib: 1.15.1

**What Happens**:  
Crash when trying to create a world with jjthunder king of the hills

//Please send logs even if you don't have any crash  
crash report:
https://pastebin.com/GvwiDWa6
logs:
https://pastebin.com/iJxYsZA7

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yep, only Iguana Tweaks, Insane lib and JJthunder king of the hills.

**Comment by Insane96** [comment]
Check the pinned issue, might be the same problem

**Comment by A4AAAAAA** [comment]
Yep, that fixed it. Thanks for answer and for that great mod, love that it adds difficulty with so much configuration options :)
