### ISSUE TITLE
Mod Name Shows as "Natural Nether Portals"

### ISSUE THREAD

**Issue by BranTuna** [Insane-96/IguanaTweaksReborn#33]
# Overview
Mod Name Shows up as "Natural Nether Portals" when loaded. Eh, not so bad.

### Version Info
**IguanaTweaksReborn** _Version 1.2.3_
**Minecraft** _Version 1.12.x (1.12.2)_

**Comment by Insane-96** [comment]
Totally not copied the build file from the other mod.
