### ISSUE TITLE
"CollideWithWall" impacts MSPT regardless of the config

### ISSUE THREAD

**Issue by BigHit3** [Insane-96/IguanaTweaksReborn#330]
**Versions**:
* Minecraft: 1.20.1
* Forge:  47.3.22
* IguanaTweaks Reborn:  3.21.4
* InsaneLib: 1.15.1

**What Happens**:  
Collide with wall feature does it's math no matter how i configure the config, even if literallt every part of ITR is disabled, it still eats MSPT.

insane96mcp.iguanatweaksreborn.module.misc.tweaks.Tweaks.onCollideWithWall()**2.34%**
net.minecraft.world.entity.LivingEntity$$Lambda$19886/0x00000281cd420d98.call()**2.33%**
net.minecraft.world.entity.LivingEntity.mixinextras$bridge$m_21074_$424()**2.32%**
net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement()**2.32%**
net.minecraft.world.entity.Entity.move()**2.19%**

https://spark.lucko.me/YQXCoIQwvE

In my test i just stood still for 1m after the world was generated and afterthat walked another 1m in 5x5 circle, everything from ITR was disabled but it still affected by MSPT.

**Config**:
**just everything disabled, especially misceleanous, tweaks and collide set to 0**:  

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
<Not tested, but probably yes>

**Comment by Insane96** [comment]
That's just calling the vanilla method so that's the vanilla method affecting MSPT

**Comment by BigHit3** [comment]
So this vanilla method is present anyway, ITR just makes it visible in Spark, right?

**Comment by Insane96** [comment]
Yep, because it calls it when it's disabled.
