### ISSUE TITLE
Reduced item stack sizes results in not being able to trade with some Villagers

### ISSUE THREAD

**Issue by imIrony** [Insane-96/IguanaTweaksReborn#36]
Limited stack sizes per items such as Emeralds prevents the player from trading with Villagers asking for more than stackable Emerald items.

**Comment by Insane-96** [comment]
I really don't know how to fix this other than making emeralds stack up to 64 again.

Please report any item that cannot be traded due to stack size changes.

**Comment by imIrony** [comment]
The only items that are affected by this include Paper, Rotten Flesh and Emeralds. I don't know whether or not it would be possible for items to stack to 64 exclusively within inventory slots in the Villager trading interface. I guess a solution would be to just whitelist those items to stack to 64 in the config by default.

**Comment by Insane-96** [comment]
> I don't know whether or not it would be possible for items to stack to 64 exclusively within inventory slots in the Villager trading interface

I think there's a field to set that, sadly items will still stack up to their maximum.

> whitelist those items to stack to 64 in the config by default

So I think this will be the solution for now
