### ISSUE TITLE
Blank screen after creating world

### ISSUE THREAD

**Issue by xhatz** [Insane-96/IguanaTweaksReborn#37]
Hello!

So I've updated my pack and did a few tests with the mods, and I figured out I was not able to create a world anymore! After the "Loading World" message disappears, nothing happens... the screen remains frozen onto the Minecraft background with no text anymore, and nothing loads.

After manually closing the window, here's the only bit of log I could found:
`[15:59:42] [Netty Server IO #1/INFO] [FML]: Rejecting connection CLIENT: IguanaTweaks: Requires version between 1.3.0 and 1.3.1 (inclusive) but client has 1.3.2.
[15:59:42] [Netty Server IO #1/ERROR] [FML]: Network Disconnect: Server Mod rejections:
IguanaTweaks: Requires version between 1.3.0 and 1.3.1 (inclusive) but client has 1.3.2.`

Thank you! (I tried disabling the mod and then it works fine :/)

**Comment by Insane-96** [comment]
Fixed in f481706 1.3.3
