### ISSUE TITLE
ModuleSleepRespawn uses net.minecraft.client.resources.I18n

### ISSUE THREAD

**Issue by professorg** [Insane-96/IguanaTweaksReborn#42]
Unless the issue is a suggestion, for crashes and bugs follow the following guideline. Not following this will result in ignored and closed issue.

Minecraft Version: 1.12.2

Mod Version: 1.3.5

Forge Version: 14.23.4.2703

What Happens:
Interacting with a bed to sleep in it does not let the player sleep in it on an SMP server. Spawn point is set correctly. Server shows errors in console. I believe I18n is not supported server side.

Logs / Crash reports (use Pastebin):
https://pastebin.com/kzB9nLg3

Config (if needed): N/A

List of mods installed / modpack:
https://pastebin.com/3w3BnmUH

**Comment by professorg** [comment]
I hacked together a quick fix by replacing I18n with TextComponentTranslation. This seems to have worked. I don't know which of the modules that use I18n are called from the client only, though. I'll submit a pull request once I figure everything out.

**Comment by Insane-96** [comment]
Thanks you so much
