### ISSUE TITLE
Survival world creation crash

### ISSUE THREAD

**Issue by Zamanry** [Insane-96/IguanaTweaksReborn#44]
Minecraft Version: 1.10.2

Mod Version: 1.3.5

Forge Version: 12.18.3.2511

What Happens: I have encountered this crash twice. Once when I was using /gamemode 0 to change to survival from creative, the game froze and crashed. Secondly, I created a new survival world and crashed during the world generation screen. Did not have an issue loading Tinkers/Mantle only. I am using the latest Java 8 version.

Logs / Crash reports (use Pastebin): https://pastebin.com/9L5sqwCP

Config (if needed): N/A

List of mods installed / modpack: 

TConstruct-1.10.2-2.6.5
Mantle-1.10.2-1.1.5

**Comment by Insane-96** [comment]
Found another bug thanks to this issue.

Sent over curse 1.3.6 with this bug fixed
