### ISSUE TITLE
Server crash (calls client code on the server)

### ISSUE THREAD

**Issue by svitoos** [Insane-96/IguanaTweaksReborn#45]
Minecraft Version:
1.12.2
Mod Version:
1.3.7
Forge Version:
1.12.2-14.23.4.2705
What Happens:
Server crash (calls client code on the server)
Logs / Crash reports (use Pastebin):
https://pastebin.com/4nJKNP4V
Config (if needed):

List of mods installed / modpack: 
see the crashreport

**Comment by Insane-96** [comment]
Fixed in 1.3.8
