### ISSUE TITLE
Suggestion - Movement/Swimming Modifier 

### ISSUE THREAD

**Issue by XvBUSHvX** [Insane-96/IguanaTweaksReborn#47]
Full disclosure I just discovered the mod and have not taken the opportunity test to see if these even need to be requested because I'm in a different stage of developing a pack. If these are already features feel free to simply close this issue and I apologize for any inconvenience in advance.

With the movement modifiers from materials I didn't notice anything about movement through water 1 block deep. which I could think would slow you down as well. Though there is sand, I do not know if the combination of sand and water should stack but that is your discretion. 

Additionally I could see encumbrance from weight and armor affecting ones ability to swim in water deeper than 1 block. This could include a slow swim speed to the complete loss of the ability to swim. The loss of ability should probably be restricted if heavier armor is worn and not simply encumbrance. Would kinda suck suck to not only have to take your armor off but leave it at the bottom of water lol. 

And if these do sound like interesting features, I'll leave how to approach the same concept with lava entirely up to you.

Thanks for you time and work on what appears to be a very exciting mod.

**Comment by Insane-96** [comment]
I need to test this but you *should* move slower in water with encumbrance, armor and blocks below you.

I'm not sure if I want to remove the slowdown when walking in a 1 deep water block since you're still walking and not swimming. Unless you're not touching the ground, in that case I should remove the slowdown for blocks below you. I need to do lots of tests.

**Comment by XvBUSHvX** [comment]
I haven't observed a bug. I haven't played using the mod yet. 

I was simply reading the available information on the mod didn't see anything mentioning it. I just thought it would be a good suggestion if it didn't already exist.

The idea is to increase the encumbered slow down when walking in water.

And removing the ability to swim if encumbered too greatly.

**Comment by Insane-96** [comment]
The plan is to make the player slower when in water (since now water completely ignores movement speed, but thanks to a recent forge update this is possible). Plus, you'll no longer be able to swim up if you're fully encumbered.

**Comment by XvBUSHvX** [comment]
sweet look forward to seeing it action, thank you for all your work.
