### ISSUE TITLE
Make hitting mobs with Fists have no knockback (Suggestion)

### ISSUE THREAD

**Issue by SirAron111** [Insane-96/IguanaTweaksReborn#60]
I really like the tweaks that you can make with this mod.

I think an option to remove the knockback from the payer who doesn’t use a tool (or with the attack speed bar not fully filled (slower fill up time for fists)) would be a nice addition. For example its way to easy to fight mobs by just spamming the hit key and pushing them into a corner they can’t even respond to that. 

Would it be possible to add something like this?

**Comment by Insane-96** [comment]
Love the idea. I'll check what I can do 👍

**Comment by SirAron111** [comment]
If it would be possible to at least disable attacking completely when the attack speed meter isn’t fully charged (to prevent spam clicking) that would already be good enough for me.

Since there are many ways to get attack speed increases like Redstone on tinkers weapons or increasing attack speed with the abilities mod I have in the pack. This would make it harder on early game to do think like abuse rapiers or just spam hit with your fist to fight mobs.

I remember that better with mods did something to disable knockback with fists but that doesn’t really matter that mod did alot of lagy things so i removed it.

PS: My pack isn’t a professional one it’s something I do in my free time XD I constantly have some ideas I would like to add but since I am not a Modder I can’t do that.

For example I really wish that I could somehow spawn rifts that sometimes appear and spawn mobs to fit the story of the pack but atm all I can do to make this somehow seem like that’s the case I have naturally generating nether portals, randomly spawning thaumcraft rifts and the dimensional rifts from dim doors mod they would be the best for this but they are only ambient atm growing in size if you don’t close them and make it seem like they are dangerous but actually aren’t.

But do have fun and feel free to join the discord if you need help people there are really nice and helpful. And thx for listening to this idea anyway.

**Comment by Insane-96** [comment]
> If it would be possible to at least disable attacking completely when the attack speed meter isn’t fully charged (to prevent spam clicking) that would already be good enough for me.

That's another problem since seems like the method that should return the attack meter / cooldown / whatever, doesn't work properly.
BUT, I've found a solution. That's now how it works. (Copy pasted from the config comment 😝)
`If the player has an item that deals no damage (so with fist, or even a stick) the attacked mob will take almost no damage (1/20 of a hearth) and no knockback. That applies even if the player attack speed cooldown is below 50%`

**Comment by Insane-96** [comment]
Closed via https://github.com/Insane-96/IguanaTweaksReborn/commit/b052c7b4e2f2ed2aedef0aee322f0547982f8c47 and https://github.com/Insane-96/IguanaTweaksReborn/commit/99d50954fb80c5168b32e272537cce6b2af0ce28
