### ISSUE TITLE
Crash when picking up ItemBlocks with meta that does not map to a blockstate

### ISSUE THREAD

**Issue by gegy1000** [Insane-96/IguanaTweaksReborn#62]
Minecraft Version: 1.12.2
Mod Version: 1.4.1
Forge Version: 14.23.5.2768

We received this crash to Midnight from a user, when picking up [this block](https://github.com/Cryptic-Mushroom/The-Midnight/blob/master/src/main/java/com/mushroom/midnight/common/block/BlockMidnightFungiShelf.java): https://pastebin.com/raw/QJ8r9f7X
After looking into it, it seems [this line](https://github.com/Insane-96/IguanaTweaksReborn/blob/6de9e3969b293ea7ee67a444802d9bfdc0f3026e/common/net/insane96mcp/iguanatweaks/modules/ModuleMovementRestriction.java#L119) causes the crash due to deserializing the blockstate with the item meta, but not considering how the block would actually be created from that metadata value. With the Midnight Shelf block, it uses the regular `EnumFacing` lookup for metadata. However, it doesn't allow the `DOWN` facing variant, which happens to map to the metadata for this item, thus causing a crash. While this can be resolved on our side, it seems it should be addressed here too to prevent other possible issues.

The ideal solution would be to replace the call to `getStateFromMeta` with `getStateForPlacement`, as this would be more accurate. However, this variable does not seem to be used so it could possibly be removed instead.

Thanks!

**Comment by Insane-96** [comment]
> However, this variable does not seem to be used so it could possibly be removed instead.

Yep that call is useless. Fixing it for 1.4.2
