### ISSUE TITLE
Some mobs dont retaliate when attacked

### ISSUE THREAD

**Issue by SirAron111** [Insane-96/IguanaTweaksReborn#63]
Unless the issue is a suggestion, for crashes and bugs follow the following guideline. Not following this will result in ignored and closed issue.

Minecraft Version:1.12.2

Mod Version:[1.12.x] IguanaTweaks Reborn 1.4.2

Forge Version:14.23.5.2768 

What Happens:with the new version some mobs dont attack(defend themselfes) if not hit with a weapon (fists or anything that isnt a sword) especialy mobs from grimoir of gaia and some of other mods that are neutral before they get attacked. you can just stand there next to them hitting them with a fether or fist untill they are dead and they wont do anything using a sword and they instantly come at you. meybe you left some random development code in there when tring out the other idea

Logs / Crash reports (use Pastebin):

Config (if needed):

List of mods installed / modpack: DimensionZero modpack

**Comment by Insane-96** [comment]
Ops, I might have included the new "no weapon, no damage" code that was
buggy, revert to 1.4.1 if you had no problems with it

Il giorno dom 9 dic 2018, 17:46 SirAron111 <notifications@github.com> ha
scritto:

**Comment by Insane-96** [comment]
Actually 1.4.1 had a bug with experience with ores so you should wait for 1.4.3 😛
