### ISSUE TITLE
Huge Lag spikes when Breaking blocks with Better With mods

### ISSUE THREAD

**Issue by rinart73** [Insane-96/IguanaTweaksReborn#66]
Minecraft Version: 1.12.2

Mod Version: 1.4.3-mc1.12.x

Forge Version: 1.12.2-14.23.5.2768

What Happens: When I'm trying to break blocks (dirt for example) I get a huge FPS drop. Just say what info I need to give.

Logs / Crash reports (use Pastebin): no crashes

Config (if needed): default

List of mods installed / modpack: 
alcatrazcore-1.0.3
antiqueatlas-1.12.2-4.4.9
Aquaculture-1.12.2-1.6.8
architecturecraft-1.12-3.80
AutoRegLib-1.3-24
BackTools-1.12.2-7.0.0
BetterFps-1.4.8
BetterQuesting-3.5.282
BetterWithMods-1.12-2.3.20-1027
BiomesOPlenty-1.12.2-7.0.1.2419-universal
BirdsNests1.12.2-2.1.0
blockdrops-1.12.2-1.4.0
Born+In+A+Barn+V1.8-1.12-1.1
BurningTorch-1.0.5
Chameleon-1.12-4.1.3
ChickenChunks-1.12.2-2.4.1.73-universal
Clumps-3.1.1
CodeChickenLib-1.12.2-3.2.2.353-universal
coroutil-1.12.1-1.2.15
CraftTweaker2-1.12-4.1.13
DynamicSurroundings-1.12.2-3.5.1.0BETA
EmbersRekindled-1.12
EquipmentTooltips-1.12.2-1.0.3-4
Farseek-1.12-2.3.1
FastLeafDecay-v14
foamfix-0.10.3-1.12.2
FoodExpansion1.3.3-1.12.2
FTBLib-5.4.1.76
FTBQuests-1.4.1.115
GiacomosBookshelf-1.12.2-1.2
GiacomosFishingNet-1.12.2-1.6.1
Guide-API-1.12-2.1.8-63
HelpFixer-1.12.1-1.5.18
Hwyla-1.8.26-B41_1.12.2
iceandfire-1.6.0-1.12.2
iChunUtil-1.12.2-7.1.4
InventoryTweaks-1.63
ItemBlacklist-1.4.0
ItemFilters-1.0.1.5
IvToolkit-1.3.3-1.12
jei_1.12.2-4.13.1.225
jeivillagers-1.12-1.0.2
JustEnoughResources-1.12.2-0.8.5.27
Level+Up!+2-1.1.22-1.12
llibrary-1.7.14-1.12.2
Login_Shield-1.12.2-3-g7c6e7ac
mcpaint-1.2.4
moreoverlays-1.14-mc1.12.2
MouseTweaks-2.9-mc1.12.2
multimob-1.0.4
NaturesCompass-1.12.2-1.5.2-beta
NetherPortalFix_1.12.1-5.3.17
NoMoreRecipeConflict-0.12(1.12.2)
noRecipeBook_v1.2.2formc1.12.2
notreepunching-2.0.9
Nutrition-1.12.2-4.0.0
OpenBlocks-1.12.2-1.8
OpenModsLib-1.12.2-0.12.1
OptiFine_1.12.2_HD_U_E3
OreLib-1.12.2-3.5.1.0BETA
primitivemobs-1.2.3
Quark-r1.5-139
questbook-3.1.1-1.12
RealBench-1.12.2-1.3.3
RecurrentComplex-1.4.7
Repose-1.12-1.6.1
rustic-1.0.15
SereneSeasons-1.12.2-1.2.13-universal
SilentGear-1.12.2-0.4.2-59
SilentLib-1.12.2-3.0.9-159
StandardExpansion-3.4.148
StorageDrawers-1.12.2-5.3.8
Streams-1.12-0.4.4
supersoundmuffler-1.12.1-1.0.2.9
TimeHUD-1.12.2-7.3.0
ToughAsNails-1.12.2-3.1.0-universal
TrashSlot_1.12.1-8.4.6
twilightforest-1.12.2-3.8.689-universal
VanillaFix-1.0.10-99
Wawla-1.12.2-2.5.264
Waystones_1.12.2-4.0.67
WearableBackpacks-1.12.2-3.1.3
zombieawareness-1.12.1-1.11.14

**Comment by Insane-96** [comment]
Does removing IguanaTweaks fixes the problem?

Il giorno Mar 15 Gen 2019, 06:46 rinart73 <notifications@github.com> ha
scritto:

**Comment by rinart73** [comment]
Yes, when I remove Iguana Tweaks I have no FPS drops.
Trying to understand which mod conflicts with this one. It's not Quark, Repose or Burning Torch. Will try more later.

**Comment by Insane-96** [comment]
Could you even make a small video?

Il 15 Gen 2019 09:13, "rinart73" <notifications@github.com> ha scritto:

Yes, when I remove Iguana Tweaks I have no FPS drops.
Trying to understand which mod conflicts with this one. It's not Quark,
Repose or Burning Torch. Will try more later.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Insane-96/IguanaTweaksReborn/issues/66#issuecomment-454302442>,
or mute the thread

**Comment by rinart73** [comment]
Sorry, I don't think I can make a video of 1-2 FPS. As soon as I start to break any block I get this.

But I found which mod causes this: Better With Mods. Idk why.

**Comment by Insane-96** [comment]
I'll test it later.

**Comment by Insane-96** [comment]
You should have sent logs
