### ISSUE TITLE
Bad tool bug

### ISSUE THREAD

**Issue by LokyLive** [Insane-96/IguanaTweaksReborn#70]
Minecraft Version:
1.12.2
Mod Version: 1.4.8
Forge Version:  2784

What Happens:
 I got a problem with bad tool feature when you  try to break a block with something in hand the holded block/item is broken and i don't take damage

**Comment by Insane-96** [comment]
That's intended, you don't get damaged because you're not using your fist

**Comment by LokyLive** [comment]
Ok but if i got an item (not a tool) in hand (no empty hand) , the item in my hand is broken and desapear , take damage could be a sufficient punishment

**Comment by Insane-96** [comment]
I'll add a config for this

**Comment by Insane-96** [comment]
Fixed via b77a064
