### ISSUE TITLE
If other mod that messes with FoV is present "Prevent FoV changes" is ignored

### ISSUE THREAD

**Issue by LokyLive** [Insane-96/IguanaTweaksReborn#72]
When you're crafting something or picking item in a chest or a machine , the Encumbrance Fov update all the time , could you fix it to update the Fov when exiting Gui ?

**Comment by Insane-96** [comment]
If you have prevent fog modifier on true in the config this should not happen

**Comment by LokyLive** [comment]
After some more test , the problem isn't from the cfg files. The problem only appears in my modpack so i have to check for conflict xD

**Comment by Insane-96** [comment]
There's some other mod that changes FOV then

**Comment by Insane-96** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/304

**Comment by Insane-96** [comment]
Fixed via https://github.com/Insane-96/IguanaTweaksReborn/commit/faef81ca550f1c0cf4ac34884e21a2907a78d31b
