### ISSUE TITLE
Suggestion: Option to disable or adjust the hunger drain from being encumbered.

### ISSUE THREAD

**Issue by SirAron111** [Insane-96/IguanaTweaksReborn#73]
Suggestion: Option to disable or adjust the hunger drain from being encumbered.

Atm it’s pretty hard for players in my Modpack to wear all the different custom armors that give  a huge amount of armor as being encumbered steadily drains your hunger even when doing nothing the more encumbered you are the higher the hunger drain. 

Is it possible to add an option to adjust this feature or turn it off? (Only the passive hunger drain added by wearing armor not all hunger drain since other Mods need hunger drain to be active). I like the slowdown effect for my Modpack but the extra hunger is just too much with all the other things that manage hunger.

Hunger drain also happens with only the mod installed.

GZ SirAron

**Comment by Insane-96** [comment]
Ops
Just realized that the exaustion is based off the update tick of the player
