### ISSUE TITLE
v1.4.11 crashes a dedicated server

### ISSUE THREAD

**Issue by jerbear64** [Insane-96/IguanaTweaksReborn#74]
Unless the issue is a suggestion, for crashes and bugs follow the following guideline. Not following this will result in ignored and closed issue.

// Versions before 1.12 are not supported

Minecraft Version: 1.12.2

// Please make sure you're using the latest version before sending a report

Mod Version: 1.4.11

Forge Version: 14.23.5.2808

What Happens: Mod crashes the server at load. I'm assuming this is related to the weight tooltips added in 1.4.11, since that's client-only and this doesn't occur with 1.4.10.

//Please send logs even if you don't have any crash, and use Pastebin or similar

Logs / Crash reports:
https://paste.dimdev.org/sihupaxuje.md

//If needed
Config:
N/A in this case.

List of mods installed / modpack: 
https://paste.dimdev.org/ezinuwijux.md

**Comment by Insane-96** [comment]
Fixed via https://github.com/Insane-96/IguanaTweaksReborn/commit/fa3894068a78dd73072cdbdf0ca2de6b518d5746
