### ISSUE TITLE
The weight displayed on items doesn’t work with special armor or Constructs armory armor.

### ISSUE THREAD

**Issue by SirAron111** [Insane-96/IguanaTweaksReborn#75]
The weight displayed on constructs armory Armor is always 0.0 even thought the slowdown works fine on it. Looks like it can’t grab the armor value. Is there a way to make the weight show on these armors as well? https://minecraft.curseforge.com/projects/constructs-armory that’s the one I mean.

**Comment by Insane-96** [comment]
That's pretty strange. I'm pretty sure Constructs' Armory uses vanilla
Armor attributes. I'll check this

Il Mer 13 Mar 2019, 19:38 SirAron111 <notifications@github.com> ha scritto:
