### ISSUE TITLE
Hunger Bar

### ISSUE THREAD

**Issue by O13SC3N3** [Insane-96/IguanaTweaksReborn#77]
Recent Version Config Options missing  I:"Hide Hunger Bar"=false like previous versions,
        I:"Hide Hunger Bar Delay"=4 is still present and can be increased to remedy this for now. Also in config for the health bar shows hunger instead of health:

        # Delay (in seconds) before hiding the hunger bar
        # Min: 0
        # Max: 2147483647
        I:"Hide Health Bar Delay"=4

**Comment by Insane-96** [comment]
Ops, this happens since 1.4.0

**Comment by Insane-96** [comment]
Fixed via https://github.com/Insane-96/IguanaTweaksReborn/commit/8f3cdc3cf97b0d8f01e7bf0bf488d465ecc27d04
