### ISSUE TITLE
Weird start-up crash between Fused and Iguana Tweaks

### ISSUE THREAD

**Issue by apotheoseGrifter** [Insane-96/IguanaTweaksReborn#81]
Unless the issue is a suggestion, for crashes and bugs follow the following guideline. Not following this will result in ignored and closed issue.

// Versions before 1.12 are not supported

Minecraft Version:
1.12.2

// Please make sure you're using the latest version before sending a report

Mod Version:
1.4.14

Forge Version:
14.23.5.2825

What Happens:
When I start up Minecraft with both Fused and Iguana Tweaks Reborn, the game almost immediately crashes.

//Please send logs even if you don't have any crash, and use Pastebin or similar

Logs / Crash reports:
https://paste.dimdev.org/gimecuzewu.mccrash

(This crash report implicates FoamFix as well, but some fiddling revealed that Fused and Iguana Tweaks Reborn still crash the game even when FoamFix is removed.)

//If needed
Config:

List of mods installed / modpack:

**Comment by Insane-96** [comment]
Fused blocks have not properly implemented `getStateFromMeta()` 
Happens with BetterWithMods too https://gist.github.com/DaedalusGame/3cd9b133695a901412f01171a01d69b5

**Comment by apotheoseGrifter** [comment]
(Sorry for taking so long to get back to you.)

I see, so Fused is the problem. It's been a while since that mod updated and the issue has clearly been around for a while, but I'll try to send a bug report to them anyway once I get the time. I am not sure what the question is, though?

**Comment by Insane-96** [comment]
Wrong tag
BTW yeah, they need to properly implement `getStateFromMeta(meta)` on the blocks.
